alter table platform.companies add constraint companies_organization_id_slug_key UNIQUE (organization_id, slug);
alter table platform.founder_intelligence add constraint founder_intelligence_organization_id_domain_intelligence_ke_key UNIQUE (organization_id, domain, intelligence_key, valid_from);
alter table platform.organizations add constraint organizations_slug_key UNIQUE (slug);
alter table platform.products add constraint products_organization_id_slug_key UNIQUE (organization_id, slug);
alter table platform.projects add constraint projects_organization_id_slug_key UNIQUE (organization_id, slug);
alter table knowledge.entities add constraint entities_organization_id_entity_type_canonical_name_key UNIQUE (organization_id, entity_type, canonical_name);
alter table knowledge.entity_aliases add constraint entity_aliases_entity_id_alias_key UNIQUE (entity_id, alias);
alter table intelligence.audience_segments add constraint audience_segments_organization_id_segment_code_key UNIQUE (organization_id, segment_code);
alter table intelligence.creator_profiles add constraint creator_profiles_organization_id_name_key UNIQUE (organization_id, name);
alter table intelligence.creator_rules add constraint creator_rules_organization_id_rule_key_source_type_key UNIQUE (organization_id, rule_key, source_type);
alter table intelligence.performance_hypotheses add constraint performance_hypotheses_organization_id_hypothesis_type_mech_key UNIQUE (organization_id, hypothesis_type, mechanism_key);
alter table intelligence.performance_observations add constraint performance_observations_platform_post_id_observed_at_key UNIQUE (platform_post_id, observed_at);
alter table intelligence.preference_questions add constraint preference_questions_organization_id_question_code_key UNIQUE (organization_id, question_code);
alter table intelligence.preference_signals add constraint preference_signals_organization_id_signal_key_signal_value_key UNIQUE (organization_id, signal_key, signal_value);
alter table intelligence.showrunner_constitutions add constraint showrunner_constitutions_organization_id_version_key UNIQUE (organization_id, version);
alter table knowledge.document_chunks add constraint document_chunks_document_id_chunk_index_key UNIQUE (document_id, chunk_index);
alter table knowledge.documents add constraint documents_organization_id_checksum_key UNIQUE (organization_id, checksum);
alter table studio.asset_versions add constraint asset_versions_asset_id_version_number_key UNIQUE (asset_id, version_number);
alter table studio.authority_franchises add constraint authority_franchises_organization_id_franchise_code_key UNIQUE (organization_id, franchise_code);
alter table studio.beat_performance_observations add constraint beat_performance_observations_platform_post_id_beat_id_obse_key UNIQUE (platform_post_id, beat_id, observed_at);
alter table studio.beat_time_ranges add constraint beat_time_ranges_platform_post_id_beat_id_start_seconds_end_key UNIQUE (platform_post_id, beat_id, start_seconds, end_seconds);
alter table studio.broll_topic_queue add constraint broll_topic_queue_organization_id_position_key UNIQUE (organization_id, "position");
alter table studio.broll_topic_queue add constraint broll_topic_queue_organization_id_title_key UNIQUE (organization_id, title);
alter table studio.clip_rotation_plans add constraint clip_rotation_plans_organization_id_clip_id_key UNIQUE (organization_id, clip_id);
alter table studio.clips add constraint clips_organization_id_clip_code_key UNIQUE (organization_id, clip_code);
alter table studio.content_angle_templates add constraint content_angle_templates_organization_id_angle_code_key UNIQUE (organization_id, angle_code);
alter table studio.content_calendar add constraint content_calendar_organization_id_publish_date_slot_number_key UNIQUE (organization_id, publish_date, slot_number);
alter table studio.content_formats add constraint content_formats_organization_id_format_code_key UNIQUE (organization_id, format_code);
alter table studio.content_freebies add constraint content_freebies_organization_id_code_key UNIQUE (organization_id, code);
alter table studio.content_funnel_mappings add constraint content_funnel_mappings_organization_id_freebie_id_offer_id_key UNIQUE (organization_id, freebie_id, offer_id);
alter table studio.content_idea_dimensions add constraint content_idea_dimensions_content_idea_id_dimension_id_key UNIQUE (content_idea_id, dimension_id);
alter table studio.content_idea_scores add constraint content_idea_scores_content_idea_id_key UNIQUE (content_idea_id);
alter table studio.content_offers add constraint content_offers_organization_id_code_key UNIQUE (organization_id, code);
alter table studio.content_packages add constraint content_packages_organization_id_package_code_key UNIQUE (organization_id, package_code);
alter table studio.content_programming_rules add constraint content_programming_rules_organization_id_rule_code_key UNIQUE (organization_id, rule_code);
alter table studio.content_series add constraint content_series_organization_id_series_code_key UNIQUE (organization_id, series_code);
alter table studio.content_slate_items add constraint content_slate_items_slate_id_content_idea_id_key UNIQUE (slate_id, content_idea_id);
alter table studio.content_slate_items add constraint content_slate_items_slate_id_position_key UNIQUE (slate_id, "position");
alter table studio.content_value_dimensions add constraint content_value_dimensions_organization_id_axis_dimension_cod_key UNIQUE (organization_id, axis, dimension_code);
alter table studio.creative_experiment_variants add constraint creative_experiment_variants_experiment_id_variant_code_key UNIQUE (experiment_id, variant_code);
alter table studio.creative_lineage add constraint creative_lineage_platform_post_id_key UNIQUE (platform_post_id);
alter table studio.curricula add constraint curricula_organization_id_code_key UNIQUE (organization_id, code);
alter table studio.curriculum_lessons add constraint curriculum_lessons_curriculum_id_lesson_code_key UNIQUE (curriculum_id, lesson_code);
alter table studio.curriculum_lessons add constraint curriculum_lessons_curriculum_id_week_number_key UNIQUE (curriculum_id, week_number);
alter table studio.curriculum_phases add constraint curriculum_phases_curriculum_id_code_key UNIQUE (curriculum_id, code);
alter table studio.curriculum_phases add constraint curriculum_phases_curriculum_id_phase_number_key UNIQUE (curriculum_id, phase_number);
alter table studio.distribution_packages add constraint distribution_packages_organization_id_episode_id_clip_id_pl_key UNIQUE NULLS NOT DISTINCT (organization_id, episode_id, clip_id, platform);
alter table studio.edit_decision_specs add constraint edit_decision_specs_episode_id_version_key UNIQUE (episode_id, version);
alter table studio.episode_beats add constraint episode_beats_episode_id_beat_number_key UNIQUE (episode_id, beat_number);
alter table studio.episode_cues add constraint episode_cues_episode_id_cue_number_key UNIQUE (episode_id, cue_number);
alter table studio.episode_track_links add constraint episode_track_links_episode_id_track_id_key UNIQUE (episode_id, track_id);
alter table studio.episodes add constraint episodes_organization_id_episode_code_key UNIQUE (organization_id, episode_code);
alter table studio.format_variants add constraint format_variants_organization_id_variant_code_key UNIQUE (organization_id, variant_code);
alter table studio.media_jobs add constraint media_jobs_organization_id_idempotency_key_key UNIQUE (organization_id, idempotency_key);
alter table studio.performance_observations add constraint performance_observations_metric_id_key UNIQUE (metric_id);
alter table studio.pipeline_runs add constraint pipeline_runs_organization_id_source_asset_id_key UNIQUE (organization_id, source_asset_id);
alter table studio.pipeline_stages add constraint pipeline_stages_pipeline_run_id_stage_code_key UNIQUE (pipeline_run_id, stage_code);
alter table studio.pipeline_stages add constraint pipeline_stages_pipeline_run_id_stage_order_key UNIQUE (pipeline_run_id, stage_order);
alter table studio.production_blocks add constraint production_blocks_production_day_id_block_number_key UNIQUE (production_day_id, block_number);
alter table studio.production_days add constraint production_days_organization_id_production_code_key UNIQUE (organization_id, production_code);
alter table studio.production_postmortems add constraint production_postmortems_episode_id_key UNIQUE (episode_id);
alter table studio.production_requirements add constraint production_requirements_episode_id_requirement_type_require_key UNIQUE (episode_id, requirement_type, requirement_key);
alter table studio.publishing_jobs add constraint publishing_jobs_platform_post_id_key UNIQUE (platform_post_id);
alter table studio.publishing_templates add constraint publishing_templates_organization_id_day_of_week_slot_numbe_key UNIQUE (organization_id, day_of_week, slot_number);
alter table studio.rate_cards add constraint rate_cards_organization_id_version_package_name_key UNIQUE (organization_id, version, package_name);
alter table studio.retention_points add constraint retention_points_platform_post_id_observed_at_elapsed_ratio_key UNIQUE (platform_post_id, observed_at, elapsed_ratio);
alter table studio.series_tracks add constraint series_tracks_organization_id_series_id_track_code_key UNIQUE (organization_id, series_id, track_code);
alter table studio.sponsor_brands add constraint sponsor_brands_organization_id_brand_name_key UNIQUE (organization_id, brand_name);
alter table studio.stage_gate_policies add constraint stage_gate_policies_organization_id_stage_code_policy_versi_key UNIQUE (organization_id, stage_code, policy_version);
alter table studio.visual_characters add constraint visual_characters_organization_id_character_code_key UNIQUE (organization_id, character_code);
alter table studio.visual_environments add constraint visual_environments_organization_id_environment_code_key UNIQUE (organization_id, environment_code);
alter table studio.visual_props add constraint visual_props_organization_id_prop_code_key UNIQUE (organization_id, prop_code);
alter table studio.visual_styles add constraint visual_styles_organization_id_style_code_key UNIQUE (organization_id, style_code);
alter table studio.youtube_reach_daily add constraint youtube_reach_daily_platform_post_id_report_date_key UNIQUE (platform_post_id, report_date);
alter table research.creator_capabilities add constraint creator_capabilities_organization_id_capability_code_key UNIQUE (organization_id, capability_code);
alter table research.creator_channels add constraint creator_channels_creator_profile_id_platform_handle_key UNIQUE (creator_profile_id, platform, handle);
alter table research.creator_profile_capabilities add constraint creator_profile_capabilities_creator_profile_id_capability__key UNIQUE (creator_profile_id, capability_id);
alter table research.creator_profiles add constraint creator_profiles_organization_id_canonical_name_key UNIQUE (organization_id, canonical_name);
alter table research.research_jobs add constraint research_jobs_organization_id_research_code_key UNIQUE (organization_id, research_code);
alter table system.automation_policies add constraint automation_policies_organization_id_policy_code_key UNIQUE (organization_id, policy_code);
alter table system.automation_runs add constraint automation_runs_organization_id_idempotency_key_key UNIQUE (organization_id, idempotency_key);
alter table system.deployments add constraint deployments_deployment_name_version_environment_key UNIQUE (deployment_name, version, environment);
alter table system.integrations add constraint integrations_organization_id_integration_code_key UNIQUE (organization_id, integration_code);
alter table system.mcp_access_tokens add constraint mcp_access_tokens_refresh_token_hash_key UNIQUE (refresh_token_hash);
alter table system.mcp_access_tokens add constraint mcp_access_tokens_token_hash_key UNIQUE (token_hash);
alter table system.workflow_definitions add constraint workflow_definitions_organization_id_workflow_code_version_key UNIQUE (organization_id, workflow_code, version);
alter table system.agent_jobs add constraint agent_jobs_priority_check CHECK (((priority >= 0) AND (priority <= 100)));
alter table platform.founder_intelligence add constraint founder_intelligence_domain_check CHECK ((domain = ANY (ARRAY['preference'::text, 'feedback'::text, 'doctrine'::text, 'experience'::text, 'expertise'::text, 'constraint'::text, 'goal'::text])));
alter table platform.founder_intelligence add constraint founder_intelligence_status_check CHECK ((status = ANY (ARRAY['active'::text, 'superseded'::text, 'archived'::text])));
alter table platform.founder_intelligence add constraint founder_intelligence_strength_check CHECK ((strength = ANY (ARRAY['HARD'::text, 'STRONG'::text, 'MEDIUM'::text, 'WEAK'::text])));
alter table platform.organization_members add constraint organization_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text, 'viewer'::text])));
alter table platform.organization_members add constraint organization_members_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text, 'revoked'::text])));
alter table platform.projects add constraint projects_priority_check CHECK (((priority >= 0) AND (priority <= 100)));
alter table knowledge.claims add constraint claims_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)));
alter table knowledge.relations add constraint relations_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)));
alter table intelligence.audience_simulations add constraint audience_simulations_verdict_check CHECK ((verdict = ANY (ARRAY['pass'::text, 'weak'::text, 'fail'::text])));
alter table intelligence.creator_mechanisms add constraint creator_mechanisms_copy_risk_check CHECK ((copy_risk = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])));
alter table intelligence.creator_patterns add constraint creator_patterns_pattern_type_check CHECK ((pattern_type = ANY (ARRAY['hook'::text, 'title'::text, 'thumbnail'::text, 'retention'::text, 'participation_mechanic'::text, 'monetization'::text, 'conversion_path'::text])));
alter table intelligence.creator_profiles add constraint creator_profiles_studied_as_check CHECK ((studied_as = ANY (ARRAY['individual'::text, 'media_company'::text, 'show_format'::text])));
alter table intelligence.creator_rules add constraint creator_rules_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)));
alter table intelligence.creator_rules add constraint creator_rules_domain_check CHECK ((domain = ANY (ARRAY['planning'::text, 'performance'::text, 'whiteboard'::text, 'camera'::text, 'edit'::text, 'caption'::text, 'clip'::text, 'broll'::text, 'motion'::text, 'publishing'::text])));
alter table intelligence.creator_rules add constraint creator_rules_polarity_check CHECK ((polarity = ANY (ARRAY['prefer'::text, 'avoid'::text, 'require'::text, 'forbid'::text])));
alter table intelligence.creator_rules add constraint creator_rules_source_type_check CHECK ((source_type = ANY (ARRAY['explicit'::text, 'revision'::text, 'approval'::text, 'performance'::text])));
alter table intelligence.creator_strengths_weaknesses add constraint creator_strengths_weaknesses_kind_check CHECK ((kind = ANY (ARRAY['strength'::text, 'weakness'::text])));
alter table intelligence.planning_generation_events add constraint planning_generation_events_event_type_check CHECK ((event_type = ANY (ARRAY['generated'::text, 'gate_failed'::text, 'repaired'::text, 'human_review'::text, 'approved'::text, 'rejected'::text])));
alter table intelligence.showrunner_constitutions add constraint showrunner_constitutions_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'active'::text, 'retired'::text])));
alter table intelligence.taste_events add constraint taste_events_decision_check CHECK ((decision = ANY (ARRAY['approve'::text, 'reject'::text, 'prefer'::text, 'revise'::text, 'neutral'::text])));
alter table intelligence.taste_events add constraint taste_events_strength_check CHECK (((strength >= (0)::numeric) AND (strength <= (1)::numeric)));
alter table knowledge.memories add constraint memories_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)));
alter table knowledge.memories add constraint memories_importance_check CHECK (((importance >= 0) AND (importance <= 100)));
alter table studio.approvals add constraint approvals_check CHECK ((num_nonnulls(asset_id, episode_id, clip_id) = 1));
alter table studio.approvals add constraint approvals_stage_check CHECK ((stage = ANY (ARRAY['production'::text, 'edit'::text, 'caption'::text, 'final'::text, 'publishing'::text])));
alter table studio.approvals add constraint approvals_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'changes_requested'::text, 'rejected'::text, 'revoked'::text])));
alter table studio.asset_versions add constraint asset_versions_version_number_check CHECK ((version_number > 0));
alter table studio.beat_time_ranges add constraint beat_time_ranges_check CHECK ((end_seconds > start_seconds));
alter table studio.broll_topic_queue add constraint broll_topic_queue_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'selected'::text, 'used'::text, 'paused'::text])));
alter table studio.capture_checks add constraint capture_checks_status_check CHECK ((status = ANY (ARRAY['pass'::text, 'fail'::text, 'pickup_required'::text, 'waived'::text])));
alter table studio.claim_ledger add constraint claim_ledger_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
alter table studio.claim_ledger add constraint claim_ledger_verification_status_check CHECK ((verification_status = ANY (ARRAY['unverified'::text, 'verified'::text, 'qualified'::text, 'rejected'::text, 'first_party'::text])));
alter table studio.clip_rotation_plans add constraint clip_rotation_plans_rotation_status_check CHECK ((rotation_status = ANY (ARRAY['eligible'::text, 'held'::text, 'scheduled'::text, 'published'::text, 'retired'::text])));
alter table studio.content_calendar add constraint content_calendar_check CHECK ((num_nonnulls(episode_id, clip_id, asset_id) <= 1));
alter table studio.content_calendar add constraint content_calendar_slot_number_check CHECK (((slot_number >= 1) AND (slot_number <= 8)));
alter table studio.content_calendar add constraint content_calendar_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'ready'::text, 'scheduled'::text, 'published'::text, 'skipped'::text])));
alter table studio.content_formats add constraint content_formats_status_check CHECK ((status = ANY (ARRAY['active'::text, 'testing'::text, 'paused'::text, 'retired'::text])));
alter table studio.content_idea_dimensions add constraint content_idea_dimensions_score_check CHECK (((score >= (0)::numeric) AND (score <= (100)::numeric)));
alter table studio.content_idea_scores add constraint content_idea_scores_check CHECK ((((interest_score IS NULL) OR ((interest_score >= (0)::numeric) AND (interest_score <= (100)::numeric))) AND ((relevance_score IS NULL) OR ((relevance_score >= (0)::numeric) AND (relevance_score <= (100)::numeric))) AND ((packaging_score IS NULL) OR ((packaging_score >= (0)::numeric) AND (packaging_score <= (100)::numeric))) AND ((retention_score IS NULL) OR ((retention_score >= (0)::numeric) AND (retention_score <= (100)::numeric))) AND ((authority_score IS NULL) OR ((authority_score >= (0)::numeric) AND (authority_score <= (100)::numeric))) AND ((attention_score IS NULL) OR ((attention_score >= (0)::numeric) AND (attention_score <= (100)::numeric))) AND ((entertainment_score IS NULL) OR ((entertainment_score >= (0)::numeric) AND (entertainment_score <= (100)::numeric))) AND ((differentiation_score IS NULL) OR ((differentiation_score >= (0)::numeric) AND (differentiation_score <= (100)::numeric))) AND ((clip_yield_score IS NULL) OR ((clip_yield_score >= (0)::numeric) AND (clip_yield_score <= (100)::numeric))) AND ((commercial_value_score IS NULL) OR ((commercial_value_score >= (0)::numeric) AND (commercial_value_score <= (100)::numeric))) AND ((production_efficiency_score IS NULL) OR ((production_efficiency_score >= (0)::numeric) AND (production_efficiency_score <= (100)::numeric))) AND ((free_game_score IS NULL) OR ((free_game_score >= (0)::numeric) AND (free_game_score <= (100)::numeric))) AND ((proof_score IS NULL) OR ((proof_score >= (0)::numeric) AND (proof_score <= (100)::numeric))) AND ((lasean_advantage_score IS NULL) OR ((lasean_advantage_score >= (0)::numeric) AND (lasean_advantage_score <= (100)::numeric)))));
alter table studio.content_ideas add constraint content_ideas_urgency_check CHECK (((urgency >= 0) AND (urgency <= 100)));
alter table studio.content_learnings add constraint content_learnings_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
alter table studio.content_learnings add constraint content_learnings_learning_stage_check CHECK ((learning_stage = ANY (ARRAY['preproduction'::text, 'filming'::text, 'postproduction'::text, 'distribution'::text, 'performance'::text])));
alter table studio.content_offers add constraint content_offers_price_cents_check CHECK ((price_cents >= 0));
alter table studio.content_packages add constraint content_packages_gate_decision_check CHECK ((gate_decision = ANY (ARRAY['pass'::text, 'repair'::text, 'human_review'::text, 'reject'::text])));
alter table studio.content_packages add constraint content_packages_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'review'::text, 'ready'::text, 'approved'::text, 'rejected'::text])));
alter table studio.content_slate_items add constraint content_slate_items_position_check CHECK (("position" > 0));
alter table studio.content_value_dimensions add constraint content_value_dimensions_axis_check CHECK ((axis = ANY (ARRAY['attention'::text, 'authority'::text])));
alter table studio.creative_evaluations add constraint creative_evaluations_verdict_check CHECK ((verdict = ANY (ARRAY['pass'::text, 'repair'::text, 'kill'::text, 'human_review'::text])));
alter table studio.creative_experiments add constraint creative_experiments_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'running'::text, 'complete'::text, 'cancelled'::text])));
alter table studio.curriculum_lessons add constraint curriculum_lessons_week_number_check CHECK (((week_number >= 1) AND (week_number <= 53)));
alter table studio.distribution_packages add constraint distribution_packages_check CHECK (((episode_id IS NOT NULL) <> (clip_id IS NOT NULL)));
alter table studio.distribution_packages add constraint distribution_packages_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'ready'::text, 'scheduled'::text, 'published'::text, 'retired'::text])));
alter table studio.episode_cues add constraint episode_cues_cue_number_check CHECK ((cue_number > 0));
alter table studio.episode_reviews add constraint episode_reviews_overall_rating_check CHECK (((overall_rating IS NULL) OR ((overall_rating >= (1)::numeric) AND (overall_rating <= (10)::numeric))));
alter table studio.format_variants add constraint format_variants_attention_weight_check CHECK (((attention_weight IS NULL) OR ((attention_weight >= 0) AND (attention_weight <= 100))));
alter table studio.format_variants add constraint format_variants_authority_weight_check CHECK (((authority_weight IS NULL) OR ((authority_weight >= 0) AND (authority_weight <= 100))));
alter table studio.format_variants add constraint format_variants_item_count_check CHECK (((item_count IS NULL) OR (item_count > 0)));
alter table studio.hooks add constraint hooks_check CHECK ((num_nonnulls(idea_id, episode_id, clip_id) >= 1));
alter table studio.media_jobs add constraint media_jobs_attempts_check CHECK ((attempts >= 0));
alter table studio.media_jobs add constraint media_jobs_job_type_check CHECK ((job_type = ANY (ARRAY['upload'::text, 'proxy'::text, 'transcription'::text, 'moment_detection'::text, 'clip_render'::text, 'caption_render'::text, 'reframe'::text, 'export'::text, 'publish'::text, 'analytics_sync'::text])));
alter table studio.media_jobs add constraint media_jobs_max_attempts_check CHECK (((max_attempts >= 1) AND (max_attempts <= 20)));
alter table studio.media_jobs add constraint media_jobs_priority_check CHECK (((priority >= 1) AND (priority <= 5)));
alter table studio.media_jobs add constraint media_jobs_progress_check CHECK (((progress >= (0)::numeric) AND (progress <= (100)::numeric)));
alter table studio.media_jobs add constraint media_jobs_run_mode_check CHECK ((run_mode = ANY (ARRAY['local'::text, 'cloud_burst'::text, 'cloud'::text])));
alter table studio.media_jobs add constraint media_jobs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'claimed'::text, 'running'::text, 'awaiting_approval'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])));
alter table studio.performance_observations add constraint performance_observations_evidence_strength_check CHECK ((evidence_strength = ANY (ARRAY['snapshot'::text, 'directional'::text, 'repeatable'::text, 'validated'::text])));
alter table studio.pipeline_runs add constraint pipeline_runs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'awaiting_approval'::text, 'approved'::text, 'publishing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])));
alter table studio.pipeline_stages add constraint pipeline_stages_stage_order_check CHECK (((stage_order >= 1) AND (stage_order <= 20)));
alter table studio.pipeline_stages add constraint pipeline_stages_status_check CHECK ((status = ANY (ARRAY['blocked'::text, 'queued'::text, 'running'::text, 'completed'::text, 'failed'::text, 'skipped'::text, 'awaiting_approval'::text])));
alter table studio.production_blocks add constraint production_blocks_block_number_check CHECK ((block_number > 0));
alter table studio.production_requirements add constraint production_requirements_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'ready'::text, 'captured'::text, 'missing'::text, 'waived'::text, 'blocked'::text])));
alter table studio.publishing_templates add constraint publishing_templates_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6)));
alter table studio.publishing_templates add constraint publishing_templates_slot_number_check CHECK (((slot_number >= 1) AND (slot_number <= 8)));
alter table studio.rate_cards add constraint rate_cards_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'active'::text, 'retired'::text])));
alter table studio.retention_points add constraint retention_points_elapsed_ratio_check CHECK (((elapsed_ratio >= (0)::numeric) AND (elapsed_ratio <= (1)::numeric)));
alter table studio.review_comments add constraint review_comments_body_check CHECK ((length(TRIM(BOTH FROM body)) > 0));
alter table studio.review_comments add constraint review_comments_status_check CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text, 'dismissed'::text])));
alter table studio.review_comments add constraint review_comments_timecode_seconds_check CHECK (((timecode_seconds IS NULL) OR (timecode_seconds >= (0)::numeric)));
alter table studio.scripts add constraint scripts_check CHECK ((num_nonnulls(idea_id, episode_id, clip_id) >= 1));
alter table studio.scripts add constraint scripts_version_check CHECK ((version > 0));
alter table studio.series_tracks add constraint series_tracks_sequence_mode_check CHECK ((sequence_mode = ANY (ARRAY['standalone'::text, 'standalone_connected'::text, 'sequential'::text])));
alter table studio.slate_evaluations add constraint slate_evaluations_decision_check CHECK ((decision = ANY (ARRAY['PASS'::text, 'WARN'::text, 'REJECT'::text])));
alter table studio.sponsor_brands add constraint sponsor_brands_actual_use_status_check CHECK ((actual_use_status = ANY (ARRAY['unknown'::text, 'uses'::text, 'used_before'::text, 'would_use'::text, 'would_not_use'::text])));
alter table studio.sponsor_brands add constraint sponsor_brands_status_check CHECK ((status = ANY (ARRAY['prospect'::text, 'active'::text, 'paused'::text, 'rejected'::text])));
alter table studio.sponsor_deals add constraint sponsor_deals_status_check CHECK ((status = ANY (ARRAY['inbound'::text, 'outbound'::text, 'negotiating'::text, 'contracted'::text, 'in_production'::text, 'delivered'::text, 'paid'::text, 'declined'::text, 'cancelled'::text])));
alter table studio.sponsor_deliverables add constraint sponsor_deliverables_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'ready'::text, 'submitted'::text, 'approved'::text, 'published'::text, 'rejected'::text, 'waived'::text])));
alter table studio.takes add constraint takes_quality_rating_check CHECK (((quality_rating >= 0) AND (quality_rating <= 100)));
alter table studio.titles add constraint titles_check CHECK ((num_nonnulls(episode_id, clip_id) >= 1));
alter table research.creator_pattern_evidence add constraint creator_pattern_evidence_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric)));
alter table research.creator_pattern_evidence add constraint creator_pattern_evidence_pattern_type_check CHECK ((pattern_type = ANY (ARRAY['hook'::text, 'title'::text, 'thumbnail'::text, 'retention'::text, 'participation'::text, 'monetization'::text, 'conversion_path'::text, 'strength'::text, 'weakness'::text])));
alter table research.creator_profile_capabilities add constraint creator_profile_capabilities_strength_score_check CHECK (((strength_score IS NULL) OR ((strength_score >= (0)::numeric) AND (strength_score <= (100)::numeric))));
alter table research.research_jobs add constraint research_jobs_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
alter table research.research_jobs add constraint research_jobs_priority_check CHECK (((priority >= 0) AND (priority <= 100)));
alter table research.research_notes add constraint research_notes_confidence_check CHECK (((confidence IS NULL) OR ((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))));
alter table research.research_sources add constraint research_sources_evidence_position_check CHECK (((evidence_position IS NULL) OR (evidence_position = ANY (ARRAY['supports'::text, 'contradicts'::text, 'context'::text, 'neutral'::text]))));
alter table research.research_sources add constraint research_sources_reliability_score_check CHECK (((reliability_score IS NULL) OR ((reliability_score >= (0)::numeric) AND (reliability_score <= (1)::numeric))));
alter table system.acceptance_runs add constraint acceptance_runs_status_check CHECK ((status = ANY (ARRAY['pass'::text, 'fail'::text])));
alter table system.automation_policies add constraint automation_policies_approval_mode_check CHECK ((approval_mode = ANY (ARRAY['automatic'::text, 'required'::text, 'blocked'::text])));
alter table system.automation_policies add constraint automation_policies_trigger_type_check CHECK ((trigger_type = ANY (ARRAY['schedule'::text, 'event'::text, 'manual'::text])));
alter table system.automation_runs add constraint automation_runs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'waiting_approval'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text])));
alter table system.deployments add constraint deployments_status_check CHECK ((status = ANY (ARRAY['deploying'::text, 'healthy'::text, 'degraded'::text, 'failed'::text, 'superseded'::text])));
alter table system.integrations add constraint integrations_status_check CHECK ((status = ANY (ARRAY['disconnected'::text, 'configured'::text, 'connected'::text, 'degraded'::text, 'disabled'::text])));
alter table system.mcp_auth_codes add constraint mcp_auth_codes_code_challenge_method_check CHECK ((code_challenge_method = 'S256'::text));
alter table system.agent_jobs add constraint agent_jobs_approved_by_person_id_fkey FOREIGN KEY (approved_by_person_id) REFERENCES platform.people(id) ON DELETE SET NULL;
alter table system.agent_jobs add constraint agent_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE SET NULL;
alter table system.ai_runs add constraint ai_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE SET NULL;
alter table platform.companies add constraint companies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table platform.founder_intelligence add constraint founder_intelligence_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table platform.organization_members add constraint organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table platform.organization_members add constraint organization_members_person_id_fkey FOREIGN KEY (person_id) REFERENCES platform.people(id) ON DELETE SET NULL;
alter table platform.organization_members add constraint organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table platform.people add constraint people_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table platform.people add constraint people_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE SET NULL;
alter table platform.products add constraint products_company_id_fkey FOREIGN KEY (company_id) REFERENCES platform.companies(id) ON DELETE SET NULL;
alter table platform.products add constraint products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table platform.projects add constraint projects_company_id_fkey FOREIGN KEY (company_id) REFERENCES platform.companies(id) ON DELETE SET NULL;
alter table platform.projects add constraint projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table platform.projects add constraint projects_owner_person_id_fkey FOREIGN KEY (owner_person_id) REFERENCES platform.people(id) ON DELETE SET NULL;
alter table platform.projects add constraint projects_product_id_fkey FOREIGN KEY (product_id) REFERENCES platform.products(id) ON DELETE SET NULL;
alter table knowledge.claims add constraint claims_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table knowledge.claims add constraint claims_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES knowledge.documents(id) ON DELETE SET NULL;
alter table knowledge.claims add constraint claims_subject_entity_id_fkey FOREIGN KEY (subject_entity_id) REFERENCES knowledge.entities(id) ON DELETE CASCADE;
alter table knowledge.claims add constraint claims_supersedes_claim_id_fkey FOREIGN KEY (supersedes_claim_id) REFERENCES knowledge.claims(id) ON DELETE SET NULL;
alter table knowledge.entities add constraint entities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table knowledge.entity_aliases add constraint entity_aliases_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES knowledge.entities(id) ON DELETE CASCADE;
alter table knowledge.relations add constraint relations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table knowledge.relations add constraint relations_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES knowledge.documents(id) ON DELETE SET NULL;
alter table knowledge.relations add constraint relations_source_entity_id_fkey FOREIGN KEY (source_entity_id) REFERENCES knowledge.entities(id) ON DELETE CASCADE;
alter table knowledge.relations add constraint relations_target_entity_id_fkey FOREIGN KEY (target_entity_id) REFERENCES knowledge.entities(id) ON DELETE CASCADE;
alter table intelligence.audience_segments add constraint audience_segments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.audience_simulations add constraint audience_simulations_audience_segment_id_fkey FOREIGN KEY (audience_segment_id) REFERENCES intelligence.audience_segments(id) ON DELETE CASCADE;
alter table intelligence.audience_simulations add constraint audience_simulations_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table intelligence.audience_simulations add constraint audience_simulations_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table intelligence.audience_simulations add constraint audience_simulations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.content_feedback add constraint content_feedback_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.content_feedback add constraint content_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table intelligence.creator_mechanisms add constraint creator_mechanisms_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES intelligence.creator_profiles(id) ON DELETE CASCADE;
alter table intelligence.creator_mechanisms add constraint creator_mechanisms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.creator_patterns add constraint creator_patterns_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES intelligence.creator_profiles(id) ON DELETE CASCADE;
alter table intelligence.creator_patterns add constraint creator_patterns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.creator_profiles add constraint creator_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.creator_research_runs add constraint creator_research_runs_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES intelligence.creator_profiles(id) ON DELETE SET NULL;
alter table intelligence.creator_research_runs add constraint creator_research_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.creator_strengths_weaknesses add constraint creator_strengths_weaknesses_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES intelligence.creator_profiles(id) ON DELETE CASCADE;
alter table intelligence.creator_strengths_weaknesses add constraint creator_strengths_weaknesses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.learning_queue add constraint learning_queue_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table intelligence.learning_queue add constraint learning_queue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.learning_queue add constraint learning_queue_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table intelligence.performance_hypotheses add constraint performance_hypotheses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.planning_generation_events add constraint planning_generation_events_content_package_id_fkey FOREIGN KEY (content_package_id) REFERENCES studio.content_packages(id) ON DELETE SET NULL;
alter table intelligence.planning_generation_events add constraint planning_generation_events_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES system.workflow_runs(id) ON DELETE CASCADE;
alter table intelligence.preference_questions add constraint preference_questions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.preference_responses add constraint preference_responses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.preference_responses add constraint preference_responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES intelligence.preference_questions(id);
alter table intelligence.preference_responses add constraint preference_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table intelligence.preference_signals add constraint preference_signals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.showrunner_constitutions add constraint showrunner_constitutions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table intelligence.taste_events add constraint taste_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table knowledge.document_chunks add constraint document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES knowledge.documents(id) ON DELETE CASCADE;
alter table knowledge.document_chunks add constraint document_chunks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table knowledge.documents add constraint documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES platform.companies(id) ON DELETE SET NULL;
alter table knowledge.documents add constraint documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table knowledge.documents add constraint documents_product_id_fkey FOREIGN KEY (product_id) REFERENCES platform.products(id) ON DELETE SET NULL;
alter table knowledge.documents add constraint documents_project_id_fkey FOREIGN KEY (project_id) REFERENCES platform.projects(id) ON DELETE SET NULL;
alter table knowledge.documents add constraint documents_supersedes_document_id_fkey FOREIGN KEY (supersedes_document_id) REFERENCES knowledge.documents(id) ON DELETE SET NULL;
alter table knowledge.memories add constraint memories_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table knowledge.memories add constraint memories_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES knowledge.documents(id) ON DELETE SET NULL;
alter table knowledge.memories add constraint memories_supersedes_memory_id_fkey FOREIGN KEY (supersedes_memory_id) REFERENCES knowledge.memories(id) ON DELETE SET NULL;
alter table studio.approvals add constraint approvals_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES studio.assets(id) ON DELETE CASCADE;
alter table studio.approvals add constraint approvals_asset_version_id_fkey FOREIGN KEY (asset_version_id) REFERENCES studio.asset_versions(id) ON DELETE SET NULL;
alter table studio.approvals add constraint approvals_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE CASCADE;
alter table studio.approvals add constraint approvals_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.approvals add constraint approvals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.approvals add constraint approvals_reviewer_user_id_fkey FOREIGN KEY (reviewer_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table studio.asset_versions add constraint asset_versions_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES studio.assets(id) ON DELETE CASCADE;
alter table studio.asset_versions add constraint asset_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table studio.asset_versions add constraint asset_versions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.assets add constraint assets_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.assets add constraint assets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.assets add constraint assets_production_day_id_fkey FOREIGN KEY (production_day_id) REFERENCES studio.production_days(id) ON DELETE SET NULL;
alter table studio.assets add constraint assets_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES studio.assets(id) ON DELETE SET NULL;
alter table studio.assets add constraint assets_take_id_fkey FOREIGN KEY (take_id) REFERENCES studio.takes(id) ON DELETE SET NULL;
alter table studio.authority_franchises add constraint authority_franchises_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.beat_time_ranges add constraint beat_time_ranges_beat_id_fkey FOREIGN KEY (beat_id) REFERENCES studio.episode_beats(id) ON DELETE CASCADE;
alter table studio.beat_time_ranges add constraint beat_time_ranges_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.beat_time_ranges add constraint beat_time_ranges_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.beat_time_ranges add constraint beat_time_ranges_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table studio.capture_checks add constraint capture_checks_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.capture_checks add constraint capture_checks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.capture_checks add constraint capture_checks_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES studio.production_requirements(id) ON DELETE SET NULL;
alter table studio.capture_checks add constraint capture_checks_take_id_fkey FOREIGN KEY (take_id) REFERENCES studio.takes(id) ON DELETE CASCADE;
alter table studio.claim_ledger add constraint claim_ledger_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.claim_ledger add constraint claim_ledger_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.claim_ledger add constraint claim_ledger_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.clip_rotation_plans add constraint clip_rotation_plans_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE CASCADE;
alter table studio.clip_rotation_plans add constraint clip_rotation_plans_source_episode_id_fkey FOREIGN KEY (source_episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.clips add constraint clips_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.clips add constraint clips_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.clips add constraint clips_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES studio.assets(id) ON DELETE SET NULL;
alter table studio.content_calendar add constraint content_calendar_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES studio.assets(id) ON DELETE SET NULL;
alter table studio.content_calendar add constraint content_calendar_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE SET NULL;
alter table studio.content_calendar add constraint content_calendar_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE SET NULL;
alter table studio.content_calendar add constraint content_calendar_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.content_formats add constraint content_formats_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_funnel_mappings add constraint content_funnel_mappings_freebie_id_fkey FOREIGN KEY (freebie_id) REFERENCES studio.content_freebies(id) ON DELETE CASCADE;
alter table studio.content_funnel_mappings add constraint content_funnel_mappings_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES studio.content_offers(id) ON DELETE SET NULL;
alter table studio.content_idea_dimensions add constraint content_idea_dimensions_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.content_idea_dimensions add constraint content_idea_dimensions_dimension_id_fkey FOREIGN KEY (dimension_id) REFERENCES studio.content_value_dimensions(id) ON DELETE RESTRICT;
alter table studio.content_idea_dimensions add constraint content_idea_dimensions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_idea_scores add constraint content_idea_scores_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.content_idea_scores add constraint content_idea_scores_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_ideas add constraint content_ideas_curriculum_lesson_id_fkey FOREIGN KEY (curriculum_lesson_id) REFERENCES studio.curriculum_lessons(id) ON DELETE SET NULL;
alter table studio.content_ideas add constraint content_ideas_format_variant_id_fkey FOREIGN KEY (format_variant_id) REFERENCES studio.format_variants(id) ON DELETE SET NULL;
alter table studio.content_ideas add constraint content_ideas_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_ideas add constraint content_ideas_project_id_fkey FOREIGN KEY (project_id) REFERENCES platform.projects(id) ON DELETE SET NULL;
alter table studio.content_ideas add constraint content_ideas_repurpose_parent_id_fkey FOREIGN KEY (repurpose_parent_id) REFERENCES studio.content_ideas(id) ON DELETE SET NULL;
alter table studio.content_ideas add constraint content_ideas_series_id_fkey FOREIGN KEY (series_id) REFERENCES studio.content_series(id) ON DELETE SET NULL;
alter table studio.content_learnings add constraint content_learnings_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.content_learnings add constraint content_learnings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_learnings add constraint content_learnings_production_day_id_fkey FOREIGN KEY (production_day_id) REFERENCES studio.production_days(id) ON DELETE CASCADE;
alter table studio.content_lifecycle_events add constraint content_lifecycle_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table studio.content_lifecycle_events add constraint content_lifecycle_events_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE CASCADE;
alter table studio.content_lifecycle_events add constraint content_lifecycle_events_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.content_lifecycle_events add constraint content_lifecycle_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_lifecycle_events add constraint content_lifecycle_events_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table studio.content_metrics add constraint content_metrics_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_metrics add constraint content_metrics_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table studio.content_packages add constraint content_packages_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES system.workflow_runs(id) ON DELETE CASCADE;
alter table studio.content_series add constraint content_series_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_slate_items add constraint content_slate_items_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.content_slate_items add constraint content_slate_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_slate_items add constraint content_slate_items_slate_id_fkey FOREIGN KEY (slate_id) REFERENCES studio.content_slates(id) ON DELETE CASCADE;
alter table studio.content_slates add constraint content_slates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_state_events add constraint content_state_events_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.content_state_events add constraint content_state_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.content_value_dimensions add constraint content_value_dimensions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.creative_evaluations add constraint creative_evaluations_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.creative_evaluations add constraint creative_evaluations_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.creative_evaluations add constraint creative_evaluations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.creative_experiment_variants add constraint creative_experiment_variants_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES studio.creative_experiments(id) ON DELETE CASCADE;
alter table studio.creative_experiment_variants add constraint creative_experiment_variants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.creative_experiments add constraint creative_experiments_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.creative_experiments add constraint creative_experiments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.creative_experiments add constraint creative_experiments_winner_variant_id_fkey FOREIGN KEY (winner_variant_id) REFERENCES studio.creative_experiment_variants(id) ON DELETE SET NULL;
alter table studio.creative_lineage add constraint creative_lineage_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE SET NULL;
alter table studio.creative_lineage add constraint creative_lineage_edit_spec_id_fkey FOREIGN KEY (edit_spec_id) REFERENCES studio.edit_decision_specs(id) ON DELETE SET NULL;
alter table studio.creative_lineage add constraint creative_lineage_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.creative_lineage add constraint creative_lineage_experiment_variant_id_fkey FOREIGN KEY (experiment_variant_id) REFERENCES studio.creative_experiment_variants(id) ON DELETE SET NULL;
alter table studio.creative_lineage add constraint creative_lineage_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.creative_lineage add constraint creative_lineage_package_hypothesis_id_fkey FOREIGN KEY (package_hypothesis_id) REFERENCES studio.packaging_hypotheses(id) ON DELETE SET NULL;
alter table studio.creative_lineage add constraint creative_lineage_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table studio.curriculum_lessons add constraint curriculum_lessons_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES studio.curricula(id) ON DELETE CASCADE;
alter table studio.curriculum_lessons add constraint curriculum_lessons_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES studio.curriculum_phases(id) ON DELETE SET NULL;
alter table studio.curriculum_phases add constraint curriculum_phases_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES studio.curricula(id) ON DELETE CASCADE;
alter table studio.distribution_packages add constraint distribution_packages_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE CASCADE;
alter table studio.distribution_packages add constraint distribution_packages_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.edit_decision_specs add constraint edit_decision_specs_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.edit_decision_specs add constraint edit_decision_specs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.episode_beats add constraint episode_beats_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.episode_beats add constraint episode_beats_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.episode_cues add constraint episode_cues_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.episode_cues add constraint episode_cues_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.episode_research_jobs add constraint episode_research_jobs_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.episode_research_jobs add constraint episode_research_jobs_research_job_id_fkey FOREIGN KEY (research_job_id) REFERENCES research.research_jobs(id) ON DELETE CASCADE;
alter table studio.episode_reviews add constraint episode_reviews_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.episode_reviews add constraint episode_reviews_production_day_id_fkey FOREIGN KEY (production_day_id) REFERENCES studio.production_days(id) ON DELETE SET NULL;
alter table studio.episode_track_links add constraint episode_track_links_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.episode_track_links add constraint episode_track_links_prerequisite_episode_id_fkey FOREIGN KEY (prerequisite_episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.episode_track_links add constraint episode_track_links_track_id_fkey FOREIGN KEY (track_id) REFERENCES studio.series_tracks(id) ON DELETE CASCADE;
alter table studio.episodes add constraint episodes_format_id_fkey FOREIGN KEY (format_id) REFERENCES studio.content_formats(id) ON DELETE SET NULL;
alter table studio.episodes add constraint episodes_idea_id_fkey FOREIGN KEY (idea_id) REFERENCES studio.content_ideas(id) ON DELETE SET NULL;
alter table studio.episodes add constraint episodes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.episodes add constraint episodes_production_day_id_fkey FOREIGN KEY (production_day_id) REFERENCES studio.production_days(id) ON DELETE SET NULL;
alter table studio.episodes add constraint episodes_selected_packaging_hypothesis_id_fkey FOREIGN KEY (selected_packaging_hypothesis_id) REFERENCES studio.packaging_hypotheses(id) ON DELETE SET NULL;
alter table studio.episodes add constraint episodes_series_id_fkey FOREIGN KEY (series_id) REFERENCES studio.content_series(id) ON DELETE SET NULL;
alter table studio.format_variants add constraint format_variants_format_id_fkey FOREIGN KEY (format_id) REFERENCES studio.content_formats(id) ON DELETE SET NULL;
alter table studio.format_variants add constraint format_variants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.hooks add constraint hooks_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE CASCADE;
alter table studio.hooks add constraint hooks_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.hooks add constraint hooks_idea_id_fkey FOREIGN KEY (idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.hooks add constraint hooks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.lead_magnet_events add constraint lead_magnet_events_freebie_id_fkey FOREIGN KEY (freebie_id) REFERENCES studio.content_freebies(id) ON DELETE SET NULL;
alter table studio.lead_magnet_events add constraint lead_magnet_events_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES studio.content_offers(id) ON DELETE SET NULL;
alter table studio.media_jobs add constraint media_jobs_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE SET NULL;
alter table studio.media_jobs add constraint media_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table studio.media_jobs add constraint media_jobs_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.media_jobs add constraint media_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.media_jobs add constraint media_jobs_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES studio.assets(id) ON DELETE SET NULL;
alter table studio.packaging_hypotheses add constraint packaging_hypotheses_content_idea_id_fkey FOREIGN KEY (content_idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.packaging_hypotheses add constraint packaging_hypotheses_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.packaging_hypotheses add constraint packaging_hypotheses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.performance_observations add constraint performance_observations_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.performance_observations add constraint performance_observations_format_id_fkey FOREIGN KEY (format_id) REFERENCES studio.content_formats(id) ON DELETE SET NULL;
alter table studio.performance_observations add constraint performance_observations_metric_id_fkey FOREIGN KEY (metric_id) REFERENCES studio.content_metrics(id) ON DELETE CASCADE;
alter table studio.performance_observations add constraint performance_observations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.performance_observations add constraint performance_observations_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table studio.pipeline_events add constraint pipeline_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.pipeline_events add constraint pipeline_events_pipeline_run_id_fkey FOREIGN KEY (pipeline_run_id) REFERENCES studio.pipeline_runs(id) ON DELETE CASCADE;
alter table studio.pipeline_events add constraint pipeline_events_pipeline_stage_id_fkey FOREIGN KEY (pipeline_stage_id) REFERENCES studio.pipeline_stages(id) ON DELETE CASCADE;
alter table studio.pipeline_runs add constraint pipeline_runs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table studio.pipeline_runs add constraint pipeline_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.pipeline_runs add constraint pipeline_runs_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES studio.assets(id) ON DELETE CASCADE;
alter table studio.pipeline_stages add constraint pipeline_stages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.pipeline_stages add constraint pipeline_stages_pipeline_run_id_fkey FOREIGN KEY (pipeline_run_id) REFERENCES studio.pipeline_runs(id) ON DELETE CASCADE;
alter table studio.pipeline_stages add constraint pipeline_stages_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES studio.assets(id) ON DELETE CASCADE;
alter table studio.platform_posts add constraint platform_posts_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES studio.assets(id) ON DELETE SET NULL;
alter table studio.platform_posts add constraint platform_posts_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE SET NULL;
alter table studio.platform_posts add constraint platform_posts_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.platform_posts add constraint platform_posts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.platform_posts add constraint platform_posts_thumbnail_asset_id_fkey FOREIGN KEY (thumbnail_asset_id) REFERENCES studio.assets(id) ON DELETE SET NULL;
alter table studio.production_blocks add constraint production_blocks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.production_blocks add constraint production_blocks_production_day_id_fkey FOREIGN KEY (production_day_id) REFERENCES studio.production_days(id) ON DELETE CASCADE;
alter table studio.production_days add constraint production_days_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.production_postmortems add constraint production_postmortems_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.production_postmortems add constraint production_postmortems_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.production_requirements add constraint production_requirements_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.production_requirements add constraint production_requirements_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.publishing_jobs add constraint publishing_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.publishing_jobs add constraint publishing_jobs_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table studio.rate_cards add constraint rate_cards_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.retention_points add constraint retention_points_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.retention_points add constraint retention_points_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.retention_points add constraint retention_points_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE CASCADE;
alter table studio.review_comments add constraint review_comments_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES studio.assets(id) ON DELETE CASCADE;
alter table studio.review_comments add constraint review_comments_asset_version_id_fkey FOREIGN KEY (asset_version_id) REFERENCES studio.asset_versions(id) ON DELETE SET NULL;
alter table studio.review_comments add constraint review_comments_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table studio.review_comments add constraint review_comments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.review_comments add constraint review_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES studio.review_comments(id) ON DELETE CASCADE;
alter table studio.review_comments add constraint review_comments_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table studio.scripts add constraint scripts_approved_by_person_id_fkey FOREIGN KEY (approved_by_person_id) REFERENCES platform.people(id) ON DELETE SET NULL;
alter table studio.scripts add constraint scripts_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE CASCADE;
alter table studio.scripts add constraint scripts_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.scripts add constraint scripts_idea_id_fkey FOREIGN KEY (idea_id) REFERENCES studio.content_ideas(id) ON DELETE CASCADE;
alter table studio.scripts add constraint scripts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.series_tracks add constraint series_tracks_series_id_fkey FOREIGN KEY (series_id) REFERENCES studio.content_series(id) ON DELETE CASCADE;
alter table studio.slate_evaluations add constraint slate_evaluations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.slate_evaluations add constraint slate_evaluations_slate_id_fkey FOREIGN KEY (slate_id) REFERENCES studio.content_slates(id) ON DELETE CASCADE;
alter table studio.sponsor_brands add constraint sponsor_brands_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.sponsor_deals add constraint sponsor_deals_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES studio.sponsor_brands(id) ON DELETE CASCADE;
alter table studio.sponsor_deals add constraint sponsor_deals_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE SET NULL;
alter table studio.sponsor_deals add constraint sponsor_deals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.sponsor_deliverables add constraint sponsor_deliverables_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES studio.sponsor_deals(id) ON DELETE CASCADE;
alter table studio.sponsor_deliverables add constraint sponsor_deliverables_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.sponsor_deliverables add constraint sponsor_deliverables_platform_post_id_fkey FOREIGN KEY (platform_post_id) REFERENCES studio.platform_posts(id) ON DELETE SET NULL;
alter table studio.sponsor_performance add constraint sponsor_performance_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES studio.sponsor_deals(id) ON DELETE CASCADE;
alter table studio.sponsor_performance add constraint sponsor_performance_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.stage_gate_evaluations add constraint stage_gate_evaluations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.stage_gate_evaluations add constraint stage_gate_evaluations_pipeline_run_id_fkey FOREIGN KEY (pipeline_run_id) REFERENCES studio.pipeline_runs(id) ON DELETE CASCADE;
alter table studio.stage_gate_evaluations add constraint stage_gate_evaluations_pipeline_stage_id_fkey FOREIGN KEY (pipeline_stage_id) REFERENCES studio.pipeline_stages(id) ON DELETE CASCADE;
alter table studio.stage_gate_evaluations add constraint stage_gate_evaluations_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES studio.stage_gate_policies(id);
alter table studio.stage_gate_policies add constraint stage_gate_policies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.takes add constraint takes_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.takes add constraint takes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.takes add constraint takes_production_day_id_fkey FOREIGN KEY (production_day_id) REFERENCES studio.production_days(id) ON DELETE CASCADE;
alter table studio.thumbnails add constraint thumbnails_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES studio.assets(id) ON DELETE SET NULL;
alter table studio.thumbnails add constraint thumbnails_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.thumbnails add constraint thumbnails_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table studio.titles add constraint titles_clip_id_fkey FOREIGN KEY (clip_id) REFERENCES studio.clips(id) ON DELETE CASCADE;
alter table studio.titles add constraint titles_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES studio.episodes(id) ON DELETE CASCADE;
alter table studio.titles add constraint titles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_capabilities add constraint creator_capabilities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_channels add constraint creator_channels_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE CASCADE;
alter table research.creator_channels add constraint creator_channels_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_examples add constraint creator_examples_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE CASCADE;
alter table research.creator_examples add constraint creator_examples_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_experiments add constraint creator_experiments_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE SET NULL;
alter table research.creator_experiments add constraint creator_experiments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_formats add constraint creator_formats_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE CASCADE;
alter table research.creator_formats add constraint creator_formats_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_mechanisms add constraint creator_mechanisms_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE SET NULL;
alter table research.creator_mechanisms add constraint creator_mechanisms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_pattern_evidence add constraint creator_pattern_evidence_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE CASCADE;
alter table research.creator_pattern_evidence add constraint creator_pattern_evidence_example_id_fkey FOREIGN KEY (example_id) REFERENCES research.creator_examples(id) ON DELETE SET NULL;
alter table research.creator_pattern_evidence add constraint creator_pattern_evidence_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_profile_capabilities add constraint creator_profile_capabilities_capability_id_fkey FOREIGN KEY (capability_id) REFERENCES research.creator_capabilities(id) ON DELETE CASCADE;
alter table research.creator_profile_capabilities add constraint creator_profile_capabilities_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE CASCADE;
alter table research.creator_profile_capabilities add constraint creator_profile_capabilities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_profiles add constraint creator_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_research_runs add constraint creator_research_runs_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE CASCADE;
alter table research.creator_research_runs add constraint creator_research_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_sources add constraint creator_sources_creator_profile_id_fkey FOREIGN KEY (creator_profile_id) REFERENCES research.creator_profiles(id) ON DELETE CASCADE;
alter table research.creator_sources add constraint creator_sources_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.creator_sources add constraint creator_sources_research_run_id_fkey FOREIGN KEY (research_run_id) REFERENCES research.creator_research_runs(id) ON DELETE SET NULL;
alter table research.research_jobs add constraint research_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.research_jobs add constraint research_jobs_requested_by_person_id_fkey FOREIGN KEY (requested_by_person_id) REFERENCES platform.people(id) ON DELETE SET NULL;
alter table research.research_notes add constraint research_notes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.research_notes add constraint research_notes_research_job_id_fkey FOREIGN KEY (research_job_id) REFERENCES research.research_jobs(id) ON DELETE CASCADE;
alter table research.research_notes add constraint research_notes_source_id_fkey FOREIGN KEY (source_id) REFERENCES research.research_sources(id) ON DELETE SET NULL;
alter table research.research_sources add constraint research_sources_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table research.research_sources add constraint research_sources_research_job_id_fkey FOREIGN KEY (research_job_id) REFERENCES research.research_jobs(id) ON DELETE CASCADE;
alter table system.automation_events add constraint automation_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table system.automation_events add constraint automation_events_run_id_fkey FOREIGN KEY (run_id) REFERENCES system.automation_runs(id) ON DELETE CASCADE;
alter table system.automation_policies add constraint automation_policies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table system.automation_runs add constraint automation_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table system.automation_runs add constraint automation_runs_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES system.automation_policies(id) ON DELETE SET NULL;
alter table system.integrations add constraint integrations_connected_by_fkey FOREIGN KEY (connected_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table system.integrations add constraint integrations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table system.mcp_access_tokens add constraint mcp_access_tokens_client_id_fkey FOREIGN KEY (client_id) REFERENCES system.mcp_oauth_clients(client_id) ON DELETE CASCADE;
alter table system.mcp_access_tokens add constraint mcp_access_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table system.mcp_auth_codes add constraint mcp_auth_codes_client_id_fkey FOREIGN KEY (client_id) REFERENCES system.mcp_oauth_clients(client_id) ON DELETE CASCADE;
alter table system.mcp_auth_codes add constraint mcp_auth_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table system.workflow_definitions add constraint workflow_definitions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table system.workflow_events add constraint workflow_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table system.workflow_events add constraint workflow_events_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES system.workflow_runs(id) ON DELETE CASCADE;
alter table system.workflow_runs add constraint workflow_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES platform.organizations(id) ON DELETE CASCADE;
alter table system.workflow_runs add constraint workflow_runs_started_by_fkey FOREIGN KEY (started_by) REFERENCES auth.users(id);
alter table system.workflow_runs add constraint workflow_runs_workflow_definition_id_fkey FOREIGN KEY (workflow_definition_id) REFERENCES system.workflow_definitions(id);
