-- UncleCred Phase 01. Extensions and the schema split.
create extension if not exists vector with schema extensions;
create extension if not exists pg_net with schema extensions;
create extension if not exists pgmq;
create extension if not exists pg_cron;
create extension if not exists pgcrypto with schema extensions;
create schema if not exists platform;
create schema if not exists studio;
create schema if not exists production;
create schema if not exists publishing;
create schema if not exists intelligence;
create schema if not exists research;
create schema if not exists knowledge;
create schema if not exists system;
grant usage on schema platform,studio,production,publishing,intelligence,research,knowledge,system to authenticated, service_role;

-- Grants: new schemas get nothing by default on Supabase.
grant usage on schema platform to anon, authenticated, service_role;
grant all on all tables in schema platform to service_role;
grant all on all sequences in schema platform to service_role;
grant all on all functions in schema platform to service_role;
grant select, insert, update, delete on all tables in schema platform to authenticated;
grant usage, select on all sequences in schema platform to authenticated;
grant execute on all functions in schema platform to authenticated;
alter default privileges in schema platform grant all on tables to service_role;
alter default privileges in schema platform grant all on sequences to service_role;
alter default privileges in schema platform grant all on functions to service_role;
alter default privileges in schema platform grant select, insert, update, delete on tables to authenticated;
grant usage on schema studio to anon, authenticated, service_role;
grant all on all tables in schema studio to service_role;
grant all on all sequences in schema studio to service_role;
grant all on all functions in schema studio to service_role;
grant select, insert, update, delete on all tables in schema studio to authenticated;
grant usage, select on all sequences in schema studio to authenticated;
grant execute on all functions in schema studio to authenticated;
alter default privileges in schema studio grant all on tables to service_role;
alter default privileges in schema studio grant all on sequences to service_role;
alter default privileges in schema studio grant all on functions to service_role;
alter default privileges in schema studio grant select, insert, update, delete on tables to authenticated;
grant usage on schema production to anon, authenticated, service_role;
grant all on all tables in schema production to service_role;
grant all on all sequences in schema production to service_role;
grant all on all functions in schema production to service_role;
grant select, insert, update, delete on all tables in schema production to authenticated;
grant usage, select on all sequences in schema production to authenticated;
grant execute on all functions in schema production to authenticated;
alter default privileges in schema production grant all on tables to service_role;
alter default privileges in schema production grant all on sequences to service_role;
alter default privileges in schema production grant all on functions to service_role;
alter default privileges in schema production grant select, insert, update, delete on tables to authenticated;
grant usage on schema publishing to anon, authenticated, service_role;
grant all on all tables in schema publishing to service_role;
grant all on all sequences in schema publishing to service_role;
grant all on all functions in schema publishing to service_role;
grant select, insert, update, delete on all tables in schema publishing to authenticated;
grant usage, select on all sequences in schema publishing to authenticated;
grant execute on all functions in schema publishing to authenticated;
alter default privileges in schema publishing grant all on tables to service_role;
alter default privileges in schema publishing grant all on sequences to service_role;
alter default privileges in schema publishing grant all on functions to service_role;
alter default privileges in schema publishing grant select, insert, update, delete on tables to authenticated;
grant usage on schema intelligence to anon, authenticated, service_role;
grant all on all tables in schema intelligence to service_role;
grant all on all sequences in schema intelligence to service_role;
grant all on all functions in schema intelligence to service_role;
grant select, insert, update, delete on all tables in schema intelligence to authenticated;
grant usage, select on all sequences in schema intelligence to authenticated;
grant execute on all functions in schema intelligence to authenticated;
alter default privileges in schema intelligence grant all on tables to service_role;
alter default privileges in schema intelligence grant all on sequences to service_role;
alter default privileges in schema intelligence grant all on functions to service_role;
alter default privileges in schema intelligence grant select, insert, update, delete on tables to authenticated;
grant usage on schema research to anon, authenticated, service_role;
grant all on all tables in schema research to service_role;
grant all on all sequences in schema research to service_role;
grant all on all functions in schema research to service_role;
grant select, insert, update, delete on all tables in schema research to authenticated;
grant usage, select on all sequences in schema research to authenticated;
grant execute on all functions in schema research to authenticated;
alter default privileges in schema research grant all on tables to service_role;
alter default privileges in schema research grant all on sequences to service_role;
alter default privileges in schema research grant all on functions to service_role;
alter default privileges in schema research grant select, insert, update, delete on tables to authenticated;
grant usage on schema knowledge to anon, authenticated, service_role;
grant all on all tables in schema knowledge to service_role;
grant all on all sequences in schema knowledge to service_role;
grant all on all functions in schema knowledge to service_role;
grant select, insert, update, delete on all tables in schema knowledge to authenticated;
grant usage, select on all sequences in schema knowledge to authenticated;
grant execute on all functions in schema knowledge to authenticated;
alter default privileges in schema knowledge grant all on tables to service_role;
alter default privileges in schema knowledge grant all on sequences to service_role;
alter default privileges in schema knowledge grant all on functions to service_role;
alter default privileges in schema knowledge grant select, insert, update, delete on tables to authenticated;
grant usage on schema system to anon, authenticated, service_role;
grant all on all tables in schema system to service_role;
grant all on all sequences in schema system to service_role;
grant all on all functions in schema system to service_role;
grant select, insert, update, delete on all tables in schema system to authenticated;
grant usage, select on all sequences in schema system to authenticated;
grant execute on all functions in schema system to authenticated;
alter default privileges in schema system grant all on tables to service_role;
alter default privileges in schema system grant all on sequences to service_role;
alter default privileges in schema system grant all on functions to service_role;
alter default privileges in schema system grant select, insert, update, delete on tables to authenticated;
revoke update, delete on system.system_events from authenticated;

select pgmq.create('dre_embeddings');
select pgmq.create('dre_content_learning');
