CREATE INDEX agent_jobs_queue_idx ON system.agent_jobs USING btree (status, priority DESC, scheduled_at);
CREATE INDEX idx_agent_jobs_approved_by_person_id_fk ON system.agent_jobs USING btree (approved_by_person_id);
CREATE INDEX idx_agent_jobs_organization_id_fk ON system.agent_jobs USING btree (organization_id);
CREATE INDEX ai_runs_org_created_idx ON system.ai_runs USING btree (organization_id, created_at DESC);
CREATE INDEX companies_org_idx ON platform.companies USING btree (organization_id);
CREATE INDEX founder_intelligence_lookup_idx ON platform.founder_intelligence USING btree (organization_id, domain, intelligence_key, status);
CREATE INDEX organization_members_person_idx ON platform.organization_members USING btree (person_id) WHERE (person_id IS NOT NULL);
CREATE INDEX organization_members_user_idx ON platform.organization_members USING btree (user_id, status, organization_id);
CREATE UNIQUE INDEX people_auth_user_uidx ON platform.people USING btree (auth_user_id) WHERE (auth_user_id IS NOT NULL);
CREATE INDEX people_org_idx ON platform.people USING btree (organization_id);
CREATE INDEX products_company_idx ON platform.products USING btree (company_id);
CREATE INDEX idx_projects_company_id_fk ON platform.projects USING btree (company_id);
CREATE INDEX idx_projects_owner_person_id_fk ON platform.projects USING btree (owner_person_id);
CREATE INDEX idx_projects_product_id_fk ON platform.projects USING btree (product_id);
CREATE INDEX projects_org_status_idx ON platform.projects USING btree (organization_id, status);
CREATE INDEX claims_authority_status_idx ON knowledge.claims USING btree (organization_id, authority, status, observed_at DESC NULLS LAST);
CREATE INDEX claims_subject_predicate_idx ON knowledge.claims USING btree (subject_entity_id, predicate, status);
CREATE INDEX claims_validity_idx ON knowledge.claims USING btree (valid_from DESC, valid_until);
CREATE INDEX graph_claims_subject_predicate_status_idx ON knowledge.claims USING btree (organization_id, subject_entity_id, predicate, status, valid_from DESC NULLS LAST);
CREATE INDEX idx_claims_source_document_id_fk ON knowledge.claims USING btree (source_document_id);
CREATE INDEX idx_claims_supersedes_claim_id_fk ON knowledge.claims USING btree (supersedes_claim_id);
CREATE INDEX entities_lookup_idx ON knowledge.entities USING btree (organization_id, entity_type, canonical_name);
CREATE UNIQUE INDEX entities_org_type_key_uidx ON knowledge.entities USING btree (organization_id, entity_type, entity_key) WHERE (entity_key IS NOT NULL);
CREATE INDEX graph_entities_org_type_name_idx ON knowledge.entities USING btree (organization_id, entity_type, lower(canonical_name));
CREATE INDEX entity_aliases_alias_idx ON knowledge.entity_aliases USING btree (alias);
CREATE INDEX graph_relations_source_type_idx ON knowledge.relations USING btree (organization_id, source_entity_id, relation_type);
CREATE INDEX graph_relations_target_type_idx ON knowledge.relations USING btree (organization_id, target_entity_id, relation_type);
CREATE INDEX idx_relations_source_document_id_fk ON knowledge.relations USING btree (source_document_id);
CREATE INDEX relations_source_idx ON knowledge.relations USING btree (source_entity_id, relation_type);
CREATE INDEX relations_target_idx ON knowledge.relations USING btree (target_entity_id, relation_type);
CREATE INDEX idx_content_request_runs_episode ON intelligence.content_request_runs USING btree (episode_id) WHERE (episode_id IS NOT NULL);
CREATE INDEX idx_content_request_runs_org_created ON intelligence.content_request_runs USING btree (organization_id, created_at DESC);
CREATE INDEX creator_mechanisms_org_idx ON intelligence.creator_mechanisms USING btree (organization_id, verified);
CREATE INDEX creator_patterns_org_type_idx ON intelligence.creator_patterns USING btree (organization_id, pattern_type, verified);
CREATE INDEX creator_research_runs_org_idx ON intelligence.creator_research_runs USING btree (organization_id, created_at DESC);
CREATE INDEX creator_rules_org_domain_idx ON intelligence.creator_rules USING btree (organization_id, domain, active);
CREATE INDEX idx_learning_queue_claim ON intelligence.learning_queue USING btree (status, not_before, priority, created_at);
CREATE INDEX idx_performance_hypotheses_status ON intelligence.performance_hypotheses USING btree (organization_id, status, confidence DESC);
CREATE INDEX performance_observations_org_time_idx ON intelligence.performance_observations USING btree (organization_id, observed_at DESC);
CREATE INDEX planning_generation_events_run_idx ON intelligence.planning_generation_events USING btree (workflow_run_id, created_at);
CREATE INDEX preference_responses_signal_idx ON intelligence.preference_responses USING btree (organization_id, signal_key, created_at DESC);
CREATE INDEX revision_events_org_created_idx ON intelligence.revision_events USING btree (organization_id, created_at DESC);
CREATE UNIQUE INDEX showrunner_constitution_one_active ON intelligence.showrunner_constitutions USING btree (organization_id) WHERE (status = 'active'::text);
CREATE INDEX taste_events_dimension_idx ON intelligence.taste_events USING btree (organization_id, dimension, decision);
CREATE INDEX taste_events_org_created_idx ON intelligence.taste_events USING btree (organization_id, created_at DESC);
CREATE INDEX document_chunks_document_idx ON knowledge.document_chunks USING btree (document_id, chunk_index);
CREATE INDEX document_chunks_embedding_hnsw_idx ON knowledge.document_chunks USING hnsw (embedding extensions.vector_ip_ops) WHERE (embedding IS NOT NULL);
CREATE INDEX document_chunks_fts_idx ON knowledge.document_chunks USING gin (to_tsvector('english'::regconfig, content));
CREATE INDEX document_chunks_org_doc_idx ON knowledge.document_chunks USING btree (organization_id, document_id, chunk_index);
CREATE INDEX documents_authority_effective_idx ON knowledge.documents USING btree (authority, effective_at DESC);
CREATE INDEX documents_context_idx ON knowledge.documents USING btree (organization_id, company_id, product_id, project_id);
CREATE INDEX documents_org_authority_effective_idx ON knowledge.documents USING btree (organization_id, authority, effective_at DESC NULLS LAST);
CREATE INDEX idx_documents_company_id_fk ON knowledge.documents USING btree (company_id);
CREATE INDEX idx_documents_product_id_fk ON knowledge.documents USING btree (product_id);
CREATE INDEX idx_documents_project_id_fk ON knowledge.documents USING btree (project_id);
CREATE INDEX idx_documents_supersedes_document_id_fk ON knowledge.documents USING btree (supersedes_document_id);
CREATE INDEX idx_memories_source_document_id_fk ON knowledge.memories USING btree (source_document_id);
CREATE INDEX idx_memories_supersedes_memory_id_fk ON knowledge.memories USING btree (supersedes_memory_id);
CREATE INDEX memories_authority_status_idx ON knowledge.memories USING btree (organization_id, authority, status, valid_from DESC);
CREATE INDEX memories_org_type_idx ON knowledge.memories USING btree (organization_id, memory_type, status);
CREATE INDEX memories_org_type_status_idx ON knowledge.memories USING btree (organization_id, memory_type, status, importance DESC NULLS LAST);
CREATE INDEX approvals_queue_idx ON studio.approvals USING btree (organization_id, status, stage, created_at);
CREATE INDEX asset_versions_org_asset_idx ON studio.asset_versions USING btree (organization_id, asset_id, version_number DESC);
CREATE INDEX assets_episode_status_idx ON studio.assets USING btree (episode_id, status);
CREATE INDEX idx_assets_organization_id_fk ON studio.assets USING btree (organization_id);
CREATE INDEX idx_assets_production_day_id_fk ON studio.assets USING btree (production_day_id);
CREATE INDEX idx_assets_source_asset_id_fk ON studio.assets USING btree (source_asset_id);
CREATE INDEX idx_assets_take_id_fk ON studio.assets USING btree (take_id);
CREATE INDEX beat_performance_episode_idx ON studio.beat_performance_observations USING btree (episode_id, observed_at DESC);
CREATE INDEX beat_performance_post_idx ON studio.beat_performance_observations USING btree (platform_post_id, observed_at DESC);
CREATE INDEX idx_beat_time_ranges_post ON studio.beat_time_ranges USING btree (platform_post_id, start_seconds, end_seconds);
CREATE INDEX idx_broll_topic_queue_org_status_position ON studio.broll_topic_queue USING btree (organization_id, status, "position");
CREATE INDEX claim_ledger_episode_idx ON studio.claim_ledger USING btree (organization_id, episode_id);
CREATE INDEX idx_rotation_target ON studio.clip_rotation_plans USING btree (rotation_status, target_publish_date);
CREATE INDEX idx_clips_episode_id_fk ON studio.clips USING btree (episode_id);
CREATE INDEX idx_clips_source_asset_id_fk ON studio.clips USING btree (source_asset_id);
CREATE INDEX idx_calendar_date ON studio.content_calendar USING btree (organization_id, publish_date, slot_number);
CREATE INDEX idx_content_calendar_idea ON studio.content_calendar USING btree (content_idea_id);
CREATE INDEX idx_freebies_org_status ON studio.content_freebies USING btree (organization_id, status);
CREATE INDEX idx_funnel_map_org ON studio.content_funnel_mappings USING btree (organization_id, active, priority);
CREATE INDEX idea_dimensions_idea_idx ON studio.content_idea_dimensions USING btree (content_idea_id);
CREATE INDEX idx_idea_scores_org_authority ON studio.content_idea_scores USING btree (organization_id, authority_score DESC, attention_score DESC);
CREATE INDEX content_ideas_queue_idx ON studio.content_ideas USING btree (organization_id, status, priority_score DESC NULLS LAST);
CREATE INDEX idx_content_ideas_project_id_fk ON studio.content_ideas USING btree (project_id);
CREATE INDEX idx_content_ideas_series_id_fk ON studio.content_ideas USING btree (series_id);
CREATE INDEX idx_content_ideas_variant ON studio.content_ideas USING btree (format_variant_id);
CREATE INDEX content_learnings_episode_idx ON studio.content_learnings USING btree (episode_id, learning_stage);
CREATE UNIQUE INDEX content_learnings_org_code_uidx ON studio.content_learnings USING btree (organization_id, learning_code) WHERE (learning_code IS NOT NULL);
CREATE INDEX content_learnings_org_stage_idx ON studio.content_learnings USING btree (organization_id, learning_stage, created_at DESC);
CREATE INDEX lifecycle_events_episode_idx ON studio.content_lifecycle_events USING btree (episode_id, occurred_at DESC);
CREATE INDEX lifecycle_events_post_idx ON studio.content_lifecycle_events USING btree (platform_post_id, occurred_at DESC);
CREATE INDEX lifecycle_events_type_idx ON studio.content_lifecycle_events USING btree (organization_id, event_type, occurred_at DESC);
CREATE INDEX content_metrics_post_observed_idx ON studio.content_metrics USING btree (platform_post_id, observed_at DESC);
CREATE INDEX idx_content_metrics_organization_id_fk ON studio.content_metrics USING btree (organization_id);
CREATE INDEX idx_offers_org_status ON studio.content_offers USING btree (organization_id, status);
CREATE INDEX content_packages_org_created_idx ON studio.content_packages USING btree (organization_id, created_at DESC);
CREATE UNIQUE INDEX content_series_org_code_uq ON studio.content_series USING btree (organization_id, series_code) WHERE (series_code IS NOT NULL);
CREATE INDEX slate_items_slate_idx ON studio.content_slate_items USING btree (slate_id, "position");
CREATE INDEX content_state_events_episode_idx ON studio.content_state_events USING btree (episode_id, created_at DESC);
CREATE INDEX idx_creative_lineage_episode ON studio.creative_lineage USING btree (episode_id);
CREATE INDEX idx_distribution_clip ON studio.distribution_packages USING btree (clip_id, platform);
CREATE INDEX idx_distribution_episode ON studio.distribution_packages USING btree (episode_id, platform);
CREATE INDEX idx_episode_beats_episode_number ON studio.episode_beats USING btree (episode_id, beat_number);
CREATE INDEX episode_cues_org_episode_idx ON studio.episode_cues USING btree (organization_id, episode_id, cue_number);
CREATE INDEX idx_episode_research_jobs_research_job_id_fk ON studio.episode_research_jobs USING btree (research_job_id);
CREATE INDEX episode_reviews_episode_idx ON studio.episode_reviews USING btree (episode_id, created_at DESC);
CREATE INDEX episode_reviews_org_idx ON studio.episode_reviews USING btree (organization_id, created_at DESC);
CREATE INDEX episodes_format_id_idx ON studio.episodes USING btree (format_id);
CREATE UNIQUE INDEX episodes_org_code_uq ON studio.episodes USING btree (organization_id, episode_code);
CREATE INDEX episodes_production_idx ON studio.episodes USING btree (production_day_id, status);
CREATE INDEX idx_episodes_idea_id_fk ON studio.episodes USING btree (idea_id);
CREATE INDEX idx_episodes_production_state ON studio.episodes USING btree (production_state);
CREATE INDEX idx_episodes_series_id_fk ON studio.episodes USING btree (series_id);
CREATE INDEX idx_format_variants_org_family ON studio.format_variants USING btree (organization_id, format_family, solo_capable, operator_required, status);
CREATE INDEX hooks_episode_selected_idx ON studio.hooks USING btree (episode_id, selected, score DESC NULLS LAST);
CREATE UNIQUE INDEX hooks_episode_variant_uq ON studio.hooks USING btree (episode_id, variant_label) WHERE ((episode_id IS NOT NULL) AND (variant_label IS NOT NULL));
CREATE INDEX idx_hooks_clip_id_fk ON studio.hooks USING btree (clip_id);
CREATE INDEX idx_hooks_idea_id_fk ON studio.hooks USING btree (idea_id);
CREATE INDEX idx_hooks_organization_id_fk ON studio.hooks USING btree (organization_id);
CREATE INDEX idx_lead_magnet_events_org_created ON studio.lead_magnet_events USING btree (organization_id, created_at DESC);
CREATE INDEX media_jobs_asset_idx ON studio.media_jobs USING btree (source_asset_id, created_at DESC);
CREATE INDEX media_jobs_episode_idx ON studio.media_jobs USING btree (episode_id, created_at DESC);
CREATE UNIQUE INDEX media_jobs_org_idempotency_idx ON studio.media_jobs USING btree (organization_id, idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX media_jobs_queue_idx ON studio.media_jobs USING btree (organization_id, status, priority, available_at, created_at) WHERE (status = ANY (ARRAY['queued'::text, 'failed'::text]));
CREATE INDEX packaging_hypotheses_episode_idx ON studio.packaging_hypotheses USING btree (organization_id, episode_id);
CREATE INDEX performance_observations_episode_idx ON studio.performance_observations USING btree (episode_id, observed_at DESC);
CREATE INDEX performance_observations_format_idx ON studio.performance_observations USING btree (format_id, observed_at DESC);
CREATE INDEX pipeline_events_run_idx ON studio.pipeline_events USING btree (pipeline_run_id, created_at);
CREATE INDEX pipeline_stages_claim_idx ON studio.pipeline_stages USING btree (status, available_at, stage_order);
CREATE INDEX idx_platform_posts_asset_id_fk ON studio.platform_posts USING btree (asset_id);
CREATE INDEX idx_platform_posts_clip_id_fk ON studio.platform_posts USING btree (clip_id);
CREATE INDEX idx_platform_posts_episode_id_fk ON studio.platform_posts USING btree (episode_id);
CREATE INDEX idx_platform_posts_thumbnail_asset_id_fk ON studio.platform_posts USING btree (thumbnail_asset_id);
CREATE INDEX platform_posts_schedule_idx ON studio.platform_posts USING btree (organization_id, platform, status, scheduled_at);
CREATE INDEX idx_production_blocks_organization_id_fk ON studio.production_blocks USING btree (organization_id);
CREATE INDEX production_blocks_day_status_idx ON studio.production_blocks USING btree (production_day_id, status, block_number);
CREATE UNIQUE INDEX production_days_org_code_uq ON studio.production_days USING btree (organization_id, production_code);
CREATE INDEX idx_production_requirements_episode_status ON studio.production_requirements USING btree (episode_id, status, required);
CREATE INDEX idx_publishing_jobs_organization_id_fk ON studio.publishing_jobs USING btree (organization_id);
CREATE INDEX publishing_jobs_status_schedule_idx ON studio.publishing_jobs USING btree (status, scheduled_at);
CREATE INDEX review_comments_asset_idx ON studio.review_comments USING btree (organization_id, asset_id, created_at);
CREATE INDEX idx_scripts_approved_by_person_id_fk ON studio.scripts USING btree (approved_by_person_id);
CREATE INDEX idx_scripts_clip_id_fk ON studio.scripts USING btree (clip_id);
CREATE INDEX idx_scripts_idea_id_fk ON studio.scripts USING btree (idea_id);
CREATE INDEX idx_scripts_organization_id_fk ON studio.scripts USING btree (organization_id);
CREATE INDEX scripts_episode_idx ON studio.scripts USING btree (episode_id, status, version DESC);
CREATE INDEX idx_series_tracks_series ON studio.series_tracks USING btree (series_id, active, sort_order);
CREATE INDEX stage_gate_eval_stage_idx ON studio.stage_gate_evaluations USING btree (pipeline_stage_id, created_at DESC);
CREATE UNIQUE INDEX ux_stage_gate_evaluation_attempt ON studio.stage_gate_evaluations USING btree (pipeline_stage_id, policy_id, attempt_number);
CREATE INDEX idx_takes_episode_id_fk ON studio.takes USING btree (episode_id);
CREATE INDEX idx_takes_organization_id_fk ON studio.takes USING btree (organization_id);
CREATE INDEX idx_takes_production_day_id_fk ON studio.takes USING btree (production_day_id);
CREATE INDEX idx_thumbnails_asset_id_fk ON studio.thumbnails USING btree (asset_id);
CREATE INDEX idx_thumbnails_organization_id_fk ON studio.thumbnails USING btree (organization_id);
CREATE INDEX thumbnails_episode_selected_idx ON studio.thumbnails USING btree (episode_id, selected, status);
CREATE UNIQUE INDEX thumbnails_episode_variant_uq ON studio.thumbnails USING btree (episode_id, variant_label);
CREATE INDEX idx_titles_clip_id_fk ON studio.titles USING btree (clip_id);
CREATE INDEX idx_titles_organization_id_fk ON studio.titles USING btree (organization_id);
CREATE INDEX titles_episode_platform_idx ON studio.titles USING btree (episode_id, platform, selected);
CREATE UNIQUE INDEX titles_episode_variant_uq ON studio.titles USING btree (episode_id, variant_label) WHERE ((episode_id IS NOT NULL) AND (variant_label IS NOT NULL));
CREATE INDEX youtube_reach_daily_episode_post_idx ON studio.youtube_reach_daily USING btree (platform_post_id, report_date DESC);
CREATE INDEX idx_creator_capabilities_org_category ON research.creator_capabilities USING btree (organization_id, category, status);
CREATE INDEX creator_mechanisms_creator_idx ON research.creator_mechanisms USING btree (creator_profile_id, category, status);
CREATE INDEX idx_creator_mechanisms_organization_id_fk ON research.creator_mechanisms USING btree (organization_id);
CREATE INDEX creator_evidence_profile_type_idx ON research.creator_pattern_evidence USING btree (creator_profile_id, pattern_type);
CREATE INDEX idx_creator_profile_capability_profile ON research.creator_profile_capabilities USING btree (creator_profile_id);
CREATE INDEX creator_sources_profile_idx ON research.creator_sources USING btree (creator_profile_id, captured_at DESC);
CREATE INDEX idx_research_jobs_requested_by_person_id_fk ON research.research_jobs USING btree (requested_by_person_id);
CREATE INDEX research_jobs_org_status_priority_idx ON research.research_jobs USING btree (organization_id, status, priority DESC NULLS LAST);
CREATE INDEX idx_research_notes_organization_id_fk ON research.research_notes USING btree (organization_id);
CREATE INDEX idx_research_notes_source_id_fk ON research.research_notes USING btree (source_id);
CREATE INDEX research_notes_job_idx ON research.research_notes USING btree (research_job_id, verified);
CREATE INDEX idx_research_sources_organization_id_fk ON research.research_sources USING btree (organization_id);
CREATE INDEX research_sources_job_idx ON research.research_sources USING btree (research_job_id, authority, published_at DESC NULLS LAST);
CREATE INDEX acceptance_runs_org_created_idx ON system.acceptance_runs USING btree (organization_id, created_at DESC);
CREATE INDEX automation_events_run_idx ON system.automation_events USING btree (run_id, created_at DESC);
CREATE INDEX automation_runs_claim_idx ON system.automation_runs USING btree (status, available_at, created_at) WHERE (status = ANY (ARRAY['queued'::text, 'failed'::text]));
CREATE INDEX mcp_access_tokens_refresh_hash_idx ON system.mcp_access_tokens USING btree (refresh_token_hash) WHERE (revoked_at IS NULL);
CREATE INDEX mcp_access_tokens_token_hash_idx ON system.mcp_access_tokens USING btree (token_hash) WHERE (revoked_at IS NULL);
CREATE INDEX mcp_auth_codes_expiry_idx ON system.mcp_auth_codes USING btree (expires_at);
