-- Ported from LaSeanPickens dre_* schemas. Source of truth: harvest citation in HARVEST-MAP.md.
create table system.agent_jobs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  agent_name text not null,
  job_type text not null,
  status text default 'queued'::text not null,
  priority smallint default 50 not null,
  input_payload jsonb default '{}'::jsonb not null,
  output_payload jsonb,
  approval_required boolean default false not null,
  approved_by_person_id uuid,
  approved_at timestamp with time zone,
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  attempts integer default 0 not null,
  last_error text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint agent_jobs_pkey PRIMARY KEY (id)
);
create table system.ai_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  run_type text not null,
  provider text,
  model text,
  prompt_version text,
  request_id text,
  actor_type text,
  actor_id text,
  input_summary text,
  input_payload jsonb,
  output_payload jsonb,
  status text default 'started'::text not null,
  input_tokens bigint,
  output_tokens bigint,
  estimated_cost numeric(14,6),
  latency_ms integer,
  error text,
  created_at timestamp with time zone default now() not null,
  completed_at timestamp with time zone,
  constraint ai_runs_pkey PRIMARY KEY (id)
);
create table platform.companies (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  name text not null,
  slug citext,
  company_type text,
  industry text,
  website text,
  description text,
  status platform.record_status default 'active'::platform.record_status not null,
  founded_at date,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint companies_pkey PRIMARY KEY (id)
);
create table platform.founder_intelligence (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  domain text not null,
  intelligence_key text not null,
  statement text not null,
  strength text default 'MEDIUM'::text not null,
  source_type text default 'direct_user_feedback'::text not null,
  source_ref text,
  evidence jsonb default '{}'::jsonb not null,
  valid_from date default CURRENT_DATE not null,
  valid_to date,
  status text default 'active'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint founder_intelligence_pkey PRIMARY KEY (id)
);
create table platform.organization_members (
  organization_id uuid not null,
  user_id uuid not null,
  person_id uuid,
  role text default 'member'::text not null,
  status text default 'active'::text not null,
  permissions jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint organization_members_pkey PRIMARY KEY (organization_id, user_id)
);
create table platform.organizations (
  id uuid default gen_random_uuid() not null,
  name text not null,
  slug citext not null,
  legal_name text,
  description text,
  status platform.record_status default 'active'::platform.record_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint organizations_pkey PRIMARY KEY (id)
);
create table platform.people (
  id uuid default gen_random_uuid() not null,
  organization_id uuid,
  auth_user_id uuid,
  canonical_name text not null,
  preferred_name text,
  email citext,
  role_title text,
  person_type text,
  status platform.record_status default 'active'::platform.record_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint people_pkey PRIMARY KEY (id)
);
create table platform.products (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  company_id uuid,
  name text not null,
  slug citext,
  product_type text,
  lifecycle_stage text,
  description text,
  repository_url text,
  production_url text,
  status platform.record_status default 'active'::platform.record_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint products_pkey PRIMARY KEY (id)
);
create table platform.projects (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  company_id uuid,
  product_id uuid,
  name text not null,
  slug citext,
  project_type text,
  objective text,
  status platform.work_status default 'idea'::platform.work_status not null,
  priority smallint,
  owner_person_id uuid,
  started_at timestamp with time zone,
  target_at timestamp with time zone,
  completed_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  description text,
  constraint projects_pkey PRIMARY KEY (id)
);
create table knowledge.claims (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  subject_entity_id uuid not null,
  predicate text not null,
  value jsonb not null,
  status knowledge.claim_status default 'active'::knowledge.claim_status not null,
  confidence numeric(4,3),
  source_document_id uuid,
  source_type text,
  source_id text,
  observed_at timestamp with time zone,
  valid_from timestamp with time zone,
  valid_until timestamp with time zone,
  supersedes_claim_id uuid,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  authority knowledge.memory_authority default 'authoritative_fact'::knowledge.memory_authority not null,
  constraint claims_pkey PRIMARY KEY (id)
);
create table knowledge.entities (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  entity_type text not null,
  canonical_name text not null,
  description text,
  canonical_record_type text,
  canonical_record_id uuid,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  entity_key text,
  constraint entities_pkey PRIMARY KEY (id)
);
create table knowledge.entity_aliases (
  id uuid default gen_random_uuid() not null,
  entity_id uuid not null,
  alias citext not null,
  alias_type text,
  created_at timestamp with time zone default now() not null,
  constraint entity_aliases_pkey PRIMARY KEY (id)
);
create table knowledge.relations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  source_entity_id uuid not null,
  relation_type text not null,
  target_entity_id uuid not null,
  confidence numeric(4,3),
  valid_from timestamp with time zone,
  valid_until timestamp with time zone,
  source_document_id uuid,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint relations_pkey PRIMARY KEY (id)
);
create table intelligence.audience_segments (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  segment_code text not null,
  name text not null,
  priority smallint default 1 not null,
  description text not null,
  jobs_to_be_done jsonb default '[]'::jsonb not null,
  tensions jsonb default '[]'::jsonb not null,
  language jsonb default '{}'::jsonb not null,
  disqualifiers jsonb default '[]'::jsonb not null,
  status text default 'active'::text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint audience_segments_pkey PRIMARY KEY (id)
);
create table intelligence.audience_simulations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  content_idea_id uuid,
  episode_id uuid,
  audience_segment_id uuid not null,
  package_snapshot jsonb default '{}'::jsonb not null,
  opening_snapshot text,
  stop_reason text,
  click_reason text,
  swipe_point text,
  confusion text,
  feels_like_school boolean,
  feels_like_guru boolean,
  expected_next text,
  share_target text,
  score numeric,
  verdict text not null,
  model text,
  created_at timestamp with time zone default now() not null,
  constraint audience_simulations_pkey PRIMARY KEY (id)
);
create table intelligence.content_feedback (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  user_id uuid not null,
  subject_type text not null,
  subject_id uuid,
  decision text not null,
  reasons text[] default '{}'::text[] not null,
  note text,
  attributes jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint content_feedback_pkey PRIMARY KEY (id)
);
create table intelligence.content_request_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  user_id uuid not null,
  request_text text not null,
  request_type text default 'auto'::text not null,
  status text default 'generated'::text not null,
  model text,
  retrieval_query text,
  evidence_chunk_ids text[] default '{}'::text[] not null,
  preference_snapshot jsonb default '[]'::jsonb not null,
  feedback_snapshot jsonb default '[]'::jsonb not null,
  retrieval_snapshot jsonb default '[]'::jsonb not null,
  output_json jsonb default '{}'::jsonb not null,
  episode_id uuid,
  created_at timestamp with time zone default now() not null,
  constraint content_request_runs_pkey PRIMARY KEY (id)
);
create table intelligence.creator_mechanisms (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  mechanism_name text not null,
  mechanism_description text not null,
  lasean_adaptation text,
  copy_risk text default 'medium'::text not null,
  use_case text[] default '{}'::text[] not null,
  evidence jsonb default '[]'::jsonb not null,
  verified boolean default false not null,
  source_url text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint creator_mechanisms_pkey PRIMARY KEY (id)
);
create table intelligence.creator_patterns (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  pattern_type text not null,
  description text not null,
  evidence jsonb default '[]'::jsonb not null,
  verified boolean default false not null,
  source_url text,
  created_at timestamp with time zone default now() not null,
  constraint creator_patterns_pkey PRIMARY KEY (id)
);
create table intelligence.creator_profiles (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  name text not null,
  studied_as text not null,
  category text[] default '{}'::text[] not null,
  summary text,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  constraint creator_profiles_pkey PRIMARY KEY (id)
);
create table intelligence.creator_research_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid,
  run_type text not null,
  query text not null,
  findings jsonb default '[]'::jsonb not null,
  sources_count integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  constraint creator_research_runs_pkey PRIMARY KEY (id)
);
create table intelligence.creator_rules (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  rule_key text not null,
  rule_text text not null,
  domain text not null,
  polarity text not null,
  source_type text not null,
  confidence numeric default 1 not null,
  evidence_count integer default 1 not null,
  evidence jsonb default '[]'::jsonb not null,
  active boolean default true not null,
  last_confirmed_at timestamp with time zone default now() not null,
  constraint creator_rules_pkey PRIMARY KEY (id)
);
create table intelligence.creator_strengths_weaknesses (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  kind text not null,
  description text not null,
  evidence jsonb default '[]'::jsonb not null,
  verified boolean default false not null,
  created_at timestamp with time zone default now() not null,
  constraint creator_strengths_weaknesses_pkey PRIMARY KEY (id)
);
create table intelligence.learning_queue (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  platform_post_id uuid,
  job_type text not null,
  status text default 'queued'::text not null,
  priority smallint default 5 not null,
  not_before timestamp with time zone default now() not null,
  attempts integer default 0 not null,
  input_snapshot jsonb default '{}'::jsonb not null,
  output jsonb default '{}'::jsonb not null,
  last_error text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint learning_queue_pkey PRIMARY KEY (id)
);
create table intelligence.performance_hypotheses (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  hypothesis_type text not null,
  mechanism_key text not null,
  statement text not null,
  evidence_episode_ids uuid[] default '{}'::uuid[] not null,
  evidence_post_ids uuid[] default '{}'::uuid[] not null,
  sample_size integer default 0 not null,
  supporting_count integer default 0 not null,
  contradicting_count integer default 0 not null,
  confidence numeric default 0 not null,
  status text default 'observation'::text not null,
  evidence jsonb default '{}'::jsonb not null,
  last_observed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint performance_hypotheses_pkey PRIMARY KEY (id)
);
create table intelligence.performance_observations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  platform_post_id uuid,
  asset_id uuid,
  clip_id uuid,
  observed_at timestamp with time zone default now() not null,
  metrics jsonb not null,
  audience_quality jsonb default '{}'::jsonb not null,
  interpretation jsonb default '{}'::jsonb not null,
  source text not null,
  constraint performance_observations_pkey PRIMARY KEY (id)
);
create table intelligence.planning_generation_events (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  workflow_run_id uuid not null,
  content_package_id uuid,
  attempt integer default 1 not null,
  event_type text not null,
  model text,
  evidence_chunk_ids text[] default '{}'::text[] not null,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint planning_generation_events_pkey PRIMARY KEY (id)
);
create table intelligence.preference_questions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  question_code text not null,
  prompt text not null,
  question_type text not null,
  options jsonb default '[]'::jsonb not null,
  signal_key text not null,
  context text default 'general'::text not null,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  constraint preference_questions_pkey PRIMARY KEY (id)
);
create table intelligence.preference_responses (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  user_id uuid not null,
  question_id uuid not null,
  signal_key text not null,
  answer jsonb not null,
  context jsonb default '{}'::jsonb not null,
  source text default 'explicit'::text not null,
  created_at timestamp with time zone default now() not null,
  constraint preference_responses_pkey PRIMARY KEY (id)
);
create table intelligence.preference_signals (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  signal_key text not null,
  signal_value text not null,
  weight numeric(6,3) default 0 not null,
  positive_count integer default 0 not null,
  negative_count integer default 0 not null,
  evidence_count integer default 0 not null,
  confidence numeric(5,4) default 0 not null,
  last_evidence_at timestamp with time zone,
  updated_at timestamp with time zone default now() not null,
  constraint preference_signals_pkey PRIMARY KEY (id)
);
create table intelligence.revision_events (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  user_id uuid,
  subject_type text not null,
  subject_id uuid,
  pipeline_run_id uuid,
  stage_code text,
  before_state jsonb default '{}'::jsonb not null,
  requested_change text not null,
  after_state jsonb default '{}'::jsonb not null,
  change_tags text[] default '{}'::text[] not null,
  accepted boolean,
  created_at timestamp with time zone default now() not null,
  constraint revision_events_pkey PRIMARY KEY (id)
);
create table intelligence.showrunner_constitutions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  version integer default 1 not null,
  status text default 'active'::text not null,
  audience_doctrine jsonb default '{}'::jsonb not null,
  brand_doctrine jsonb default '{}'::jsonb not null,
  attention_doctrine jsonb default '{}'::jsonb not null,
  authority_doctrine jsonb default '{}'::jsonb not null,
  tech_doctrine jsonb default '{}'::jsonb not null,
  packaging_doctrine jsonb default '{}'::jsonb not null,
  truth_doctrine jsonb default '{}'::jsonb not null,
  production_doctrine jsonb default '{}'::jsonb not null,
  sponsor_doctrine jsonb default '{}'::jsonb not null,
  release_doctrine jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint showrunner_constitutions_pkey PRIMARY KEY (id)
);
create table intelligence.taste_events (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  user_id uuid,
  subject_type text not null,
  subject_id uuid,
  comparison_subject_id uuid,
  decision text not null,
  dimension text not null,
  reason text,
  strength numeric default 1 not null,
  context jsonb default '{}'::jsonb not null,
  model_version text,
  created_at timestamp with time zone default now() not null,
  constraint taste_events_pkey PRIMARY KEY (id)
);
create table knowledge.document_chunks (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  document_id uuid not null,
  chunk_index integer not null,
  heading_path text,
  content text not null,
  token_count integer,
  source_start integer,
  source_end integer,
  embedding extensions.vector(384),
  embedding_model text,
  embedding_dimensions integer,
  embedded_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  fts tsvector,
  constraint document_chunks_pkey PRIMARY KEY (id)
);
create table knowledge.documents (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  company_id uuid,
  product_id uuid,
  project_id uuid,
  title text not null,
  document_type text,
  source_uri text,
  storage_bucket text,
  storage_path text,
  mime_type text,
  checksum text,
  version_label text,
  authority knowledge.source_authority default 'working'::knowledge.source_authority not null,
  confidentiality platform.confidentiality_level default 'internal'::platform.confidentiality_level not null,
  effective_at timestamp with time zone,
  supersedes_document_id uuid,
  ingestion_status text default 'pending'::text not null,
  raw_text text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint documents_pkey PRIMARY KEY (id)
);
create table knowledge.memories (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  subject_entity_id uuid,
  memory_type text not null,
  statement text not null,
  importance smallint,
  confidence numeric(4,3),
  source_document_id uuid,
  source_type text,
  source_id uuid,
  valid_from timestamp with time zone default now() not null,
  valid_until timestamp with time zone,
  last_used_at timestamp with time zone,
  supersedes_memory_id uuid,
  status text default 'active'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  authority knowledge.memory_authority default 'observation'::knowledge.memory_authority not null,
  constraint memories_pkey PRIMARY KEY (id)
);
create table studio.approvals (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  asset_id uuid,
  asset_version_id uuid,
  episode_id uuid,
  clip_id uuid,
  stage text not null,
  status text default 'pending'::text not null,
  reviewer_user_id uuid,
  decision_note text,
  decided_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint approvals_pkey PRIMARY KEY (id)
);
create table studio.asset_versions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  asset_id uuid not null,
  version_number integer not null,
  storage_bucket text,
  storage_path text,
  checksum text,
  duration_seconds numeric,
  change_summary text,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  metadata jsonb default '{}'::jsonb not null,
  constraint asset_versions_pkey PRIMARY KEY (id)
);
create table studio.assets (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  production_day_id uuid,
  episode_id uuid,
  take_id uuid,
  source_asset_id uuid,
  asset_type text not null,
  storage_bucket text,
  storage_path text,
  file_name text,
  mime_type text,
  duration_seconds numeric(10,3),
  checksum text,
  transcript text,
  people jsonb default '[]'::jsonb not null,
  products jsonb default '[]'::jsonb not null,
  companies jsonb default '[]'::jsonb not null,
  claims_sources jsonb default '[]'::jsonb not null,
  status platform.work_status default 'ready'::platform.work_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint assets_pkey PRIMARY KEY (id)
);
create table studio.authority_franchises (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  franchise_code text not null,
  name text not null,
  promise text not null,
  workflow_template jsonb not null,
  default_authority_dimensions text[] default '{}'::text[] not null,
  default_attention_dimensions text[] default '{}'::text[] not null,
  requires_proof boolean default true not null,
  status text default 'active'::text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint authority_franchises_pkey PRIMARY KEY (id)
);
create table studio.beat_performance_observations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  platform_post_id uuid not null,
  beat_id uuid not null,
  observed_at timestamp with time zone not null,
  start_seconds numeric not null,
  end_seconds numeric not null,
  start_audience_ratio numeric,
  end_audience_ratio numeric,
  avg_audience_ratio numeric,
  retention_delta numeric,
  relative_retention_avg numeric,
  points_used integer default 0 not null,
  alignment_confidence numeric,
  interpretation jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint beat_performance_observations_pkey PRIMARY KEY (id)
);
create table studio.beat_time_ranges (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  platform_post_id uuid,
  beat_id uuid not null,
  start_seconds numeric not null,
  end_seconds numeric not null,
  source text default 'edit_alignment'::text not null,
  confidence numeric,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint beat_time_ranges_pkey PRIMARY KEY (id)
);
create table studio.broll_topic_queue (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  position integer not null,
  title text not null,
  teaching_goal text not null,
  lane text default 'business_systems'::text not null,
  status text default 'queued'::text not null,
  selected_at timestamp with time zone,
  used_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint broll_topic_queue_pkey PRIMARY KEY (id)
);
create table studio.capture_checks (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  take_id uuid,
  requirement_id uuid,
  check_type text not null,
  status text not null,
  message text,
  timecode_start numeric,
  timecode_end numeric,
  confidence numeric,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint capture_checks_pkey PRIMARY KEY (id)
);
create table studio.claim_ledger (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  content_idea_id uuid,
  claim_text text not null,
  claim_type text default 'factual'::text not null,
  verification_status text default 'unverified'::text not null,
  source_uri text,
  source_title text,
  source_date date,
  source_chunk_id text,
  allowed_wording text,
  confidence numeric,
  visual_proof jsonb default '{}'::jsonb not null,
  expires_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint claim_ledger_pkey PRIMARY KEY (id)
);
create table studio.clip_rotation_plans (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  clip_id uuid not null,
  source_episode_id uuid not null,
  earliest_publish_date date,
  target_publish_date date,
  latest_publish_date date,
  min_gap_from_same_master_days integer default 7 not null,
  evergreen_until date,
  rotation_status text default 'eligible'::text not null,
  priority_score numeric,
  fatigue_score numeric,
  reason text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint clip_rotation_plans_pkey PRIMARY KEY (id)
);
create table studio.clips (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  source_asset_id uuid,
  clip_code text not null,
  clip_category text,
  premise text,
  hook text,
  payoff text,
  content_lane text,
  audience text,
  hook_type text,
  creator_mechanism text,
  business_objective text,
  commercial_objective text,
  cta text,
  start_time_seconds numeric(10,3),
  end_time_seconds numeric(10,3),
  status platform.work_status default 'idea'::platform.work_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint clips_pkey PRIMARY KEY (id)
);
create table studio.content_angle_templates (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  angle_code text not null,
  name text not null,
  prompt_instruction text not null,
  utility_type text,
  implementation_level text,
  default_format text,
  active boolean default true not null,
  sort_order integer default 0 not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_angle_templates_pkey PRIMARY KEY (id)
);
create table studio.content_calendar (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  publish_date date not null,
  slot_number smallint not null,
  episode_id uuid,
  clip_id uuid,
  asset_id uuid,
  content_role text,
  format_mode text,
  platform_targets text[] default '{}'::text[] not null,
  status text default 'planned'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  content_idea_id uuid,
  constraint content_calendar_pkey PRIMARY KEY (id)
);
create table studio.content_formats (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  format_code text not null,
  name text not null,
  description text,
  format_family text,
  primary_audience text,
  retention_mechanic text,
  participation_mechanic text,
  default_runtime_seconds integer,
  default_item_min integer,
  default_item_max integer,
  authority_role text,
  commercial_role text,
  fatigue_window_days integer default 30,
  status text default 'active'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_formats_pkey PRIMARY KEY (id)
);
create table studio.content_freebies (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  code text not null,
  name text not null,
  category text not null,
  audience text,
  problem text,
  promise text not null,
  delivery_format text default 'checklist'::text not null,
  contents jsonb default '[]'::jsonb not null,
  cta text,
  status text default 'draft'::text not null,
  fact_check_required boolean default false not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_freebies_pkey PRIMARY KEY (id)
);
create table studio.content_funnel_mappings (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  freebie_id uuid not null,
  offer_id uuid,
  topic_keywords text[] default '{}'::text[] not null,
  funnel_stage text default 'value_to_offer'::text not null,
  cta text,
  priority integer default 100 not null,
  active boolean default true not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_funnel_mappings_pkey PRIMARY KEY (id)
);
create table studio.content_idea_dimensions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  content_idea_id uuid not null,
  dimension_id uuid not null,
  score numeric(5,2),
  rationale text,
  evidence jsonb default '[]'::jsonb not null,
  scored_by text default 'system'::text not null,
  scored_at timestamp with time zone default now() not null,
  constraint content_idea_dimensions_pkey PRIMARY KEY (id)
);
create table studio.content_idea_scores (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  content_idea_id uuid not null,
  interest_score numeric(5,2),
  relevance_score numeric(5,2),
  packaging_score numeric(5,2),
  retention_score numeric(5,2),
  authority_score numeric(5,2),
  attention_score numeric(5,2),
  entertainment_score numeric(5,2),
  differentiation_score numeric(5,2),
  clip_yield_score numeric(5,2),
  commercial_value_score numeric(5,2),
  production_efficiency_score numeric(5,2),
  free_game_score numeric(5,2),
  proof_score numeric(5,2),
  lasean_advantage_score numeric(5,2),
  attention_dimensions jsonb default '{}'::jsonb not null,
  authority_dimensions jsonb default '{}'::jsonb not null,
  scoring_model text,
  scored_at timestamp with time zone default now() not null,
  metadata jsonb default '{}'::jsonb not null,
  constraint content_idea_scores_pkey PRIMARY KEY (id)
);
create table studio.content_ideas (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  series_id uuid,
  project_id uuid,
  title text not null,
  premise text,
  content_lane text,
  audience text,
  hook_territory text,
  creator_mechanism text,
  business_objective text,
  commercial_objective text,
  evergreen boolean,
  urgency smallint,
  priority_score numeric(6,2),
  status platform.work_status default 'idea'::platform.work_status not null,
  evidence_needed text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  format_variant_id uuid,
  attention_dimensions text[] default '{}'::text[] not null,
  authority_dimensions text[] default '{}'::text[] not null,
  curriculum_lesson_id uuid,
  originality_class text default 'original'::text not null,
  utility_type text,
  implementation_level text,
  audience_stage text,
  face_requirement text,
  visual_family text,
  resource_candidate boolean default false not null,
  long_form_candidate boolean default false not null,
  fact_check_requirement text,
  trend_sensitivity text,
  repurpose_parent_id uuid,
  repurpose_angle text,
  caption_hook text,
  visual_hook text,
  image_prompt text,
  platform_primary text,
  platform_variants text[] default '{}'::text[] not null,
  constraint content_ideas_pkey PRIMARY KEY (id)
);
create table studio.content_learnings (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  production_day_id uuid,
  episode_id uuid,
  learning_stage text not null,
  learning_type text not null,
  statement text not null,
  evidence jsonb default '{}'::jsonb not null,
  confidence numeric,
  action_recommendation text,
  status text default 'active'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  learning_code text,
  constraint content_learnings_pkey PRIMARY KEY (id)
);
create table studio.content_lifecycle_events (
  id bigint not null,
  organization_id uuid not null,
  episode_id uuid,
  clip_id uuid,
  platform_post_id uuid,
  event_type text not null,
  from_status text,
  to_status text,
  source text default 'system'::text not null,
  actor_user_id uuid,
  metadata jsonb default '{}'::jsonb not null,
  occurred_at timestamp with time zone default now() not null,
  constraint content_lifecycle_events_pkey PRIMARY KEY (id)
);
create table studio.content_metrics (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  platform_post_id uuid not null,
  observed_at timestamp with time zone default now() not null,
  views bigint,
  reach bigint,
  impressions bigint,
  likes bigint,
  comments bigint,
  shares bigint,
  saves bigint,
  rewatches bigint,
  followers_gained bigint,
  subscribers_gained bigint,
  profile_visits bigint,
  leads bigint,
  customers bigint,
  ctr numeric(8,4),
  retention_30s numeric(8,4),
  avg_view_duration_seconds numeric(12,3),
  avg_percentage_viewed numeric(8,4),
  completion_rate numeric(8,4),
  revenue numeric(14,2),
  audience_quality_score numeric(6,2),
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint content_metrics_pkey PRIMARY KEY (id)
);
create table studio.content_offers (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  code text not null,
  name text not null,
  category text not null,
  audience text,
  problem text,
  promise text not null,
  price_cents integer default 0 not null,
  delivery_format text default 'digital_bundle'::text not null,
  includes jsonb default '[]'::jsonb not null,
  checkout_url text,
  status text default 'planned'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_offers_pkey PRIMARY KEY (id)
);
create table studio.content_packages (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  workflow_run_id uuid not null,
  package_code text not null,
  title text not null,
  status text default 'draft'::text not null,
  package_json jsonb not null,
  gate_decision text not null,
  evidence_chunk_ids text[] default '{}'::text[] not null,
  created_by uuid not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_packages_pkey PRIMARY KEY (id)
);
create table studio.content_programming_rules (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  rule_code text not null,
  rule_type text not null,
  rule_text text not null,
  rule_json jsonb default '{}'::jsonb not null,
  priority integer default 100 not null,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_programming_rules_pkey PRIMARY KEY (id)
);
create table studio.content_series (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  name text not null,
  series_code text,
  premise text,
  audience text,
  format_family text,
  business_role text,
  publishing_rhythm text,
  status platform.record_status default 'active'::platform.record_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_series_pkey PRIMARY KEY (id)
);
create table studio.content_slate_items (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  slate_id uuid not null,
  content_idea_id uuid not null,
  position integer not null,
  role text,
  created_at timestamp with time zone default now() not null,
  constraint content_slate_items_pkey PRIMARY KEY (id)
);
create table studio.content_slates (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  name text not null,
  period_start date,
  period_end date,
  status text default 'draft'::text not null,
  strategy jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint content_slates_pkey PRIMARY KEY (id)
);
create table studio.content_state_events (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  from_state text,
  to_state text not null,
  trigger_type text not null,
  trigger_id uuid,
  actor_type text default 'system'::text not null,
  reason text,
  snapshot jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint content_state_events_pkey PRIMARY KEY (id)
);
create table studio.content_value_dimensions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  axis text not null,
  dimension_code text not null,
  name text not null,
  description text,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  constraint content_value_dimensions_pkey PRIMARY KEY (id)
);
create table studio.creative_evaluations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  content_idea_id uuid,
  episode_id uuid,
  evaluation_stage text not null,
  contract_score numeric,
  truth_score numeric,
  production_score numeric,
  creative_score numeric not null,
  stop_power numeric,
  universal_relevance numeric,
  stakes_score numeric,
  curiosity_score numeric,
  novelty_score numeric,
  emotional_tension numeric,
  specificity_score numeric,
  promise_strength numeric,
  authenticity_score numeric,
  payoff_score numeric,
  hard_failures jsonb default '[]'::jsonb not null,
  verdict text not null,
  rationale text,
  model text,
  created_at timestamp with time zone default now() not null,
  constraint creative_evaluations_pkey PRIMARY KEY (id)
);
create table studio.creative_experiment_variants (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  experiment_id uuid not null,
  variant_code text not null,
  payload jsonb not null,
  outcome jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint creative_experiment_variants_pkey PRIMARY KEY (id)
);
create table studio.creative_experiments (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  experiment_type text not null,
  hypothesis text not null,
  success_metric text not null,
  status text default 'planned'::text not null,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  result_summary text,
  winner_variant_id uuid,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint creative_experiments_pkey PRIMARY KEY (id)
);
create table studio.creative_lineage (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  platform_post_id uuid,
  clip_id uuid,
  package_hypothesis_id uuid,
  edit_spec_id uuid,
  experiment_variant_id uuid,
  opening_text text,
  thumbnail_snapshot jsonb default '{}'::jsonb not null,
  package_snapshot jsonb default '{}'::jsonb not null,
  story_snapshot jsonb default '{}'::jsonb not null,
  production_snapshot jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint creative_lineage_pkey PRIMARY KEY (id)
);
create table studio.curricula (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  code text not null,
  name text not null,
  audience text,
  promise text,
  start_state text,
  end_state text,
  duration_weeks integer default 52 not null,
  status text default 'active'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint curricula_pkey PRIMARY KEY (id)
);
create table studio.curriculum_lessons (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  curriculum_id uuid not null,
  phase_id uuid,
  week_number integer not null,
  lesson_code text not null,
  title text not null,
  viewer_start_state text,
  viewer_end_state text,
  core_questions jsonb default '[]'::jsonb not null,
  required_topics jsonb default '[]'::jsonb not null,
  optional_topics jsonb default '[]'::jsonb not null,
  resource_opportunities jsonb default '[]'::jsonb not null,
  series_opportunities jsonb default '[]'::jsonb not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint curriculum_lessons_pkey PRIMARY KEY (id)
);
create table studio.curriculum_phases (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  curriculum_id uuid not null,
  phase_number integer not null,
  code text not null,
  name text not null,
  promise text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint curriculum_phases_pkey PRIMARY KEY (id)
);
create table studio.distribution_packages (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  clip_id uuid,
  platform text not null,
  title text,
  caption text default ''::text not null,
  cover_text text,
  description text,
  pinned_comment text,
  on_screen_text jsonb default '[]'::jsonb not null,
  hashtags text[] default '{}'::text[] not null,
  keywords text[] default '{}'::text[] not null,
  cta text,
  status text default 'draft'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint distribution_packages_pkey PRIMARY KEY (id)
);
create table studio.edit_decision_specs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  version integer default 1 not null,
  status text default 'draft'::text not null,
  decisions jsonb default '[]'::jsonb not null,
  source_manifest jsonb default '{}'::jsonb not null,
  story_notes jsonb default '{}'::jsonb not null,
  qc_requirements jsonb default '[]'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint edit_decision_specs_pkey PRIMARY KEY (id)
);
create table studio.episode_beats (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  beat_number integer not null,
  beat_type text not null,
  purpose text not null,
  spoken_content text,
  open_loop text,
  payoff_for text,
  emotion_target text,
  visual_plan jsonb default '{}'::jsonb not null,
  proof_claim_ids uuid[] default '{}'::uuid[] not null,
  clip_candidate boolean default false not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint episode_beats_pkey PRIMARY KEY (id)
);
create table studio.episode_cues (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  cue_number integer not null,
  operator_prompt text not null,
  default_rank text,
  default_response text,
  performance_direction text,
  planned boolean default true not null,
  actually_used boolean,
  actual_rank text,
  actual_response text,
  notes text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint episode_cues_pkey PRIMARY KEY (id)
);
create table studio.episode_research_jobs (
  episode_id uuid not null,
  research_job_id uuid not null,
  purpose text,
  created_at timestamp with time zone default now() not null,
  constraint episode_research_jobs_pkey PRIMARY KEY (episode_id, research_job_id)
);
create table studio.episode_reviews (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  production_day_id uuid,
  reviewer_person_id uuid,
  liked text,
  disliked text,
  felt_natural text,
  felt_forced text,
  keep_next_time text,
  change_next_time text,
  overall_notes text,
  overall_rating numeric,
  review_status text default 'submitted'::text not null,
  learnings_generated boolean default false not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint episode_reviews_pkey PRIMARY KEY (id)
);
create table studio.episode_track_links (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  track_id uuid not null,
  sequence_number integer,
  relationship_to_previous text,
  prerequisite_episode_id uuid,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint episode_track_links_pkey PRIMARY KEY (id)
);
create table studio.episodes (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  series_id uuid,
  idea_id uuid,
  production_day_id uuid,
  episode_code text not null,
  working_title text not null,
  audience text,
  viewer_promise text,
  why_it_exists text,
  opening text,
  first_payoff text,
  stakes text,
  central_question text,
  story_arc text,
  retention_beats jsonb default '[]'::jsonb not null,
  clip_moments jsonb default '[]'::jsonb not null,
  cta text,
  status platform.work_status default 'idea'::platform.work_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  format_id uuid,
  production_state text default 'insight'::text not null,
  creative_score numeric,
  contract_score numeric,
  truth_score numeric,
  production_score numeric,
  selected_packaging_hypothesis_id uuid,
  constraint episodes_pkey PRIMARY KEY (id)
);
create table studio.format_variants (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  format_id uuid,
  variant_code text not null,
  name text not null,
  format_family text not null,
  mechanic text not null,
  scoring_system text,
  item_count integer,
  participation_level text,
  visual_mechanic text,
  operator_required boolean default false not null,
  solo_capable boolean default true not null,
  whiteboard_required boolean default false not null,
  authority_weight smallint,
  attention_weight smallint,
  status text default 'active'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint format_variants_pkey PRIMARY KEY (id)
);
create table studio.hooks (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  idea_id uuid,
  episode_id uuid,
  clip_id uuid,
  hook_text text not null,
  hook_type text,
  variant_label text,
  score numeric,
  selected boolean default false not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint hooks_pkey PRIMARY KEY (id)
);
create table studio.lead_magnet_events (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  freebie_id uuid,
  offer_id uuid,
  event_type text not null,
  platform text,
  source_content_id uuid,
  visitor_key text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint lead_magnet_events_pkey PRIMARY KEY (id)
);
create table studio.media_jobs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  job_type text not null,
  source_asset_id uuid,
  episode_id uuid,
  clip_id uuid,
  status text default 'queued'::text not null,
  priority smallint default 3 not null,
  run_mode text default 'local'::text not null,
  provider text,
  progress numeric(5,2) default 0 not null,
  attempts smallint default 0 not null,
  max_attempts smallint default 3 not null,
  idempotency_key text,
  input jsonb default '{}'::jsonb not null,
  output jsonb default '{}'::jsonb not null,
  cost_estimate_usd numeric(10,4),
  cost_actual_usd numeric(10,4),
  error_code text,
  error_message text,
  claimed_by text,
  claimed_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  available_at timestamp with time zone default now() not null,
  created_by uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint media_jobs_pkey PRIMARY KEY (id)
);
create table studio.packaging_hypotheses (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  content_idea_id uuid,
  episode_id uuid,
  hypothesis_label text not null,
  strategy text not null,
  title text not null,
  thumbnail_concept text not null,
  thumbnail_text text,
  visual_prompt text,
  viewer_promise text not null,
  cold_viewer_reason text not null,
  selected boolean default false not null,
  score numeric,
  score_breakdown jsonb default '{}'::jsonb not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint packaging_hypotheses_pkey PRIMARY KEY (id)
);
create table studio.performance_observations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  platform_post_id uuid not null,
  metric_id uuid not null,
  episode_id uuid,
  format_id uuid,
  observed_at timestamp with time zone not null,
  views bigint,
  engagement_count bigint,
  engagement_rate numeric,
  avg_percentage_viewed numeric,
  completion_rate numeric,
  leads bigint,
  customers bigint,
  revenue numeric,
  evidence_strength text default 'snapshot'::text not null,
  interpretation jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint performance_observations_pkey PRIMARY KEY (id)
);
create table studio.pipeline_events (
  id bigint not null,
  organization_id uuid not null,
  pipeline_run_id uuid not null,
  pipeline_stage_id uuid,
  event_type text not null,
  from_status text,
  to_status text,
  actor_type text default 'system'::text not null,
  actor_ref text,
  detail jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint pipeline_events_pkey PRIMARY KEY (id)
);
create table studio.pipeline_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  source_asset_id uuid not null,
  status text default 'queued'::text not null,
  current_stage text,
  strategy jsonb default '{}'::jsonb not null,
  context_snapshot jsonb default '{}'::jsonb not null,
  error jsonb default '{}'::jsonb not null,
  created_by uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint pipeline_runs_pkey PRIMARY KEY (id)
);
create table studio.pipeline_stages (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  pipeline_run_id uuid not null,
  source_asset_id uuid not null,
  stage_order smallint not null,
  stage_code text not null,
  worker_class text not null,
  status text default 'blocked'::text not null,
  depends_on_stage_code text,
  input jsonb default '{}'::jsonb not null,
  output jsonb default '{}'::jsonb not null,
  attempts smallint default 0 not null,
  max_attempts smallint default 3 not null,
  claimed_by text,
  claimed_at timestamp with time zone,
  heartbeat_at timestamp with time zone,
  available_at timestamp with time zone default now() not null,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_code text,
  error_message text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint pipeline_stages_pkey PRIMARY KEY (id)
);
create table studio.platform_posts (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  clip_id uuid,
  asset_id uuid,
  platform text not null,
  external_post_id text,
  post_url text,
  title text,
  caption text,
  thumbnail_asset_id uuid,
  cta text,
  status platform.work_status default 'ready'::platform.work_status not null,
  scheduled_at timestamp with time zone,
  published_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint platform_posts_pkey PRIMARY KEY (id)
);
create table studio.production_blocks (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  production_day_id uuid not null,
  block_number integer not null,
  name text not null,
  block_type text,
  planned_start_at timestamp with time zone,
  planned_end_at timestamp with time zone,
  actual_start_at timestamp with time zone,
  actual_end_at timestamp with time zone,
  set_name text,
  energy_level text,
  dependencies jsonb default '[]'::jsonb not null,
  notes text,
  status platform.work_status default 'ready'::platform.work_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint production_blocks_pkey PRIMARY KEY (id)
);
create table studio.production_days (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  production_code text not null,
  production_date date not null,
  title text,
  objective text,
  status platform.work_status default 'ready'::platform.work_status not null,
  location text,
  call_time timestamp with time zone,
  wrap_time timestamp with time zone,
  notes text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint production_days_pkey PRIMARY KEY (id)
);
create table studio.production_postmortems (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  package_result jsonb default '{}'::jsonb not null,
  opening_result jsonb default '{}'::jsonb not null,
  story_result jsonb default '{}'::jsonb not null,
  visual_result jsonb default '{}'::jsonb not null,
  authority_result jsonb default '{}'::jsonb not null,
  distribution_result jsonb default '{}'::jsonb not null,
  commercial_result jsonb default '{}'::jsonb not null,
  production_result jsonb default '{}'::jsonb not null,
  taste_calibration jsonb default '{}'::jsonb not null,
  proposed_learnings jsonb default '[]'::jsonb not null,
  status text default 'draft'::text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint production_postmortems_pkey PRIMARY KEY (id)
);
create table studio.production_requirements (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  requirement_type text not null,
  requirement_key text not null,
  description text not null,
  required boolean default true not null,
  status text default 'pending'::text not null,
  owner_role text,
  dependency_ids uuid[] default '{}'::uuid[] not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint production_requirements_pkey PRIMARY KEY (id)
);
create table studio.publishing_jobs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  platform_post_id uuid not null,
  provider text,
  external_job_id text,
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  attempt_count integer default 0 not null,
  last_error text,
  status platform.work_status default 'ready'::platform.work_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint publishing_jobs_pkey PRIMARY KEY (id)
);
create table studio.publishing_templates (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  day_of_week smallint not null,
  slot_number smallint not null,
  content_role text not null,
  source_pool text not null,
  preferred_formats text[] default '{}'::text[] not null,
  platform_targets text[] default '{}'::text[] not null,
  strategic_note text,
  active boolean default true not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint publishing_templates_pkey PRIMARY KEY (id)
);
create table studio.rate_cards (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  version integer default 1 not null,
  status text default 'active'::text not null,
  package_name text not null,
  inventory jsonb not null,
  base_price numeric,
  currency text default 'USD'::text not null,
  usage_rights_pricing jsonb default '{}'::jsonb not null,
  exclusivity_pricing jsonb default '{}'::jsonb not null,
  notes text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint rate_cards_pkey PRIMARY KEY (id)
);
create table studio.retention_points (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  platform_post_id uuid not null,
  episode_id uuid,
  observed_at timestamp with time zone default now() not null,
  elapsed_ratio numeric not null,
  audience_watch_ratio numeric,
  relative_retention_performance numeric,
  metadata jsonb default '{}'::jsonb not null,
  constraint retention_points_pkey PRIMARY KEY (id)
);
create table studio.review_comments (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  asset_id uuid not null,
  asset_version_id uuid,
  parent_comment_id uuid,
  author_user_id uuid,
  timecode_seconds numeric,
  frame_annotation jsonb,
  body text not null,
  status text default 'open'::text not null,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint review_comments_pkey PRIMARY KEY (id)
);
create table studio.scripts (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  idea_id uuid,
  episode_id uuid,
  clip_id uuid,
  script_type text not null,
  version integer default 1 not null,
  content text not null,
  approved boolean default false not null,
  approved_by_person_id uuid,
  status platform.work_status default 'ready'::platform.work_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint scripts_pkey PRIMARY KEY (id)
);
create table studio.series_tracks (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  series_id uuid not null,
  track_code text not null,
  name text not null,
  premise text not null,
  strategic_role text,
  sequence_mode text default 'standalone_connected'::text not null,
  active boolean default true not null,
  sort_order integer default 100 not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint series_tracks_pkey PRIMARY KEY (id)
);
create table studio.slate_evaluations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  slate_id uuid not null,
  attention_average numeric(5,2),
  authority_average numeric(5,2),
  free_game_average numeric(5,2),
  authority_item_count integer default 0 not null,
  opinion_only_count integer default 0 not null,
  format_family_counts jsonb default '{}'::jsonb not null,
  violations jsonb default '[]'::jsonb not null,
  recommendations jsonb default '[]'::jsonb not null,
  decision text not null,
  scoring_model text default 'kaldr_slate_balance_v1'::text not null,
  evaluated_at timestamp with time zone default now() not null,
  constraint slate_evaluations_pkey PRIMARY KEY (id)
);
create table studio.sponsor_brands (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  brand_name text not null,
  category text,
  website text,
  actual_use_status text default 'unknown'::text not null,
  audience_fit_score numeric,
  trust_risk_score numeric,
  editorial_fit_notes text,
  contact jsonb default '{}'::jsonb not null,
  status text default 'prospect'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint sponsor_brands_pkey PRIMARY KEY (id)
);
create table studio.sponsor_deals (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  brand_id uuid not null,
  episode_id uuid,
  deal_name text not null,
  status text default 'inbound'::text not null,
  fee numeric,
  currency text default 'USD'::text not null,
  usage_rights jsonb default '{}'::jsonb not null,
  exclusivity jsonb default '{}'::jsonb not null,
  disclosure_requirements jsonb default '{}'::jsonb not null,
  integration_requirements jsonb default '{}'::jsonb not null,
  deadlines jsonb default '{}'::jsonb not null,
  payment_terms jsonb default '{}'::jsonb not null,
  trust_notes text,
  ai_recommendation jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint sponsor_deals_pkey PRIMARY KEY (id)
);
create table studio.sponsor_deliverables (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  deal_id uuid not null,
  platform text not null,
  deliverable_type text not null,
  quantity integer default 1 not null,
  requirements jsonb default '{}'::jsonb not null,
  due_at timestamp with time zone,
  status text default 'planned'::text not null,
  platform_post_id uuid,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint sponsor_deliverables_pkey PRIMARY KEY (id)
);
create table studio.sponsor_performance (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  deal_id uuid not null,
  observed_at timestamp with time zone default now() not null,
  metrics jsonb default '{}'::jsonb not null,
  retention_delta numeric,
  audience_sentiment jsonb default '{}'::jsonb not null,
  renewal_score numeric,
  notes text,
  created_at timestamp with time zone default now() not null,
  constraint sponsor_performance_pkey PRIMARY KEY (id)
);
create table studio.stage_gate_evaluations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  pipeline_run_id uuid not null,
  pipeline_stage_id uuid not null,
  policy_id uuid not null,
  retrieval_snapshot jsonb default '{}'::jsonb not null,
  scores jsonb default '{}'::jsonb not null,
  overall_score numeric(5,2) not null,
  hard_failures jsonb default '[]'::jsonb not null,
  decision text not null,
  remediation_plan jsonb default '{}'::jsonb not null,
  evaluated_by text not null,
  model_version text,
  created_at timestamp with time zone default now() not null,
  attempt_number smallint default 1 not null,
  constraint stage_gate_evaluations_pkey PRIMARY KEY (id)
);
create table studio.stage_gate_policies (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  stage_code text not null,
  policy_version integer default 1 not null,
  retrieval_query_template text not null,
  required_evidence_types text[] default '{}'::text[] not null,
  score_dimensions jsonb default '{}'::jsonb not null,
  minimum_overall_score numeric(5,2) default 70 not null,
  hard_fail_rules jsonb default '[]'::jsonb not null,
  remediation_actions jsonb default '[]'::jsonb not null,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  constraint stage_gate_policies_pkey PRIMARY KEY (id)
);
create table studio.takes (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  production_day_id uuid,
  take_number integer,
  take_type text,
  quality_rating smallint,
  notes text,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint takes_pkey PRIMARY KEY (id)
);
create table studio.thumbnails (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid not null,
  asset_id uuid,
  concept text not null,
  on_image_text text,
  visual_direction text,
  variant_label text,
  score numeric,
  selected boolean default false not null,
  status platform.work_status default 'ready'::platform.work_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint thumbnails_pkey PRIMARY KEY (id)
);
create table studio.titles (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  clip_id uuid,
  platform text,
  title_text text not null,
  variant_label text,
  score numeric,
  selected boolean default false not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint titles_pkey PRIMARY KEY (id)
);
create table studio.trend_queue (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  topic text not null,
  platform text,
  why_trending text,
  discovered_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone,
  relevance_bridge text,
  hook_opportunity text,
  visual_opportunity text,
  risk_notes text,
  priority_score numeric,
  status text default 'new'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint trend_queue_pkey PRIMARY KEY (id)
);
create table studio.visual_characters (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  character_code text not null,
  name text not null,
  public_name text,
  description text not null,
  age_range text,
  wardrobe jsonb default '{}'::jsonb not null,
  physical_traits jsonb default '{}'::jsonb not null,
  personality_traits jsonb default '{}'::jsonb not null,
  allowed_contexts text[] default '{}'::text[] not null,
  prohibited_changes text[] default '{}'::text[] not null,
  reference_assets jsonb default '[]'::jsonb not null,
  generation_notes text,
  active boolean default true not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint visual_characters_pkey PRIMARY KEY (id)
);
create table studio.visual_environments (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  environment_code text not null,
  name text not null,
  description text not null,
  generation_notes text,
  active boolean default true not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint visual_environments_pkey PRIMARY KEY (id)
);
create table studio.visual_props (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  prop_code text not null,
  name text not null,
  description text not null,
  generation_notes text,
  active boolean default true not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint visual_props_pkey PRIMARY KEY (id)
);
create table studio.visual_styles (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  style_code text not null,
  name text not null,
  description text not null,
  generation_notes text,
  active boolean default true not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint visual_styles_pkey PRIMARY KEY (id)
);
create table studio.youtube_reach_daily (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  platform_post_id uuid not null,
  video_id text not null,
  report_date date not null,
  impressions bigint,
  ctr_raw numeric,
  report_id text,
  report_create_time timestamp with time zone,
  source_metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  ctr_ratio numeric,
  ctr_unit_verified boolean default false not null,
  constraint youtube_reach_daily_pkey PRIMARY KEY (id)
);
create table research.creator_capabilities (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  capability_code text not null,
  category text not null,
  name text not null,
  description text,
  status text default 'active'::text not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint creator_capabilities_pkey PRIMARY KEY (id)
);
create table research.creator_channels (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  platform text not null,
  handle text,
  channel_url text,
  audience_size bigint,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint creator_channels_pkey PRIMARY KEY (id)
);
create table research.creator_examples (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  title text not null,
  source_url text,
  published_at timestamp with time zone,
  transcript_excerpt text,
  why_it_matters text,
  metrics jsonb default '{}'::jsonb not null,
  evidence jsonb default '[]'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint creator_examples_pkey PRIMARY KEY (id)
);
create table research.creator_experiments (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid,
  hypothesis text not null,
  lasean_adaptation text not null,
  success_metrics jsonb default '[]'::jsonb not null,
  status text default 'planned'::text not null,
  results jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint creator_experiments_pkey PRIMARY KEY (id)
);
create table research.creator_formats (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  format_name text not null,
  format_family text,
  mechanic text,
  description text,
  lasean_adaptation text,
  copy_risk text,
  evidence jsonb default '[]'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint creator_formats_pkey PRIMARY KEY (id)
);
create table research.creator_mechanisms (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid,
  mechanism_name text not null,
  category text,
  description text,
  why_it_works text,
  lasean_adaptation text,
  avoid text,
  trend_dependency text,
  success_metric text,
  status platform.record_status default 'active'::platform.record_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint creator_mechanisms_pkey PRIMARY KEY (id)
);
create table research.creator_pattern_evidence (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  example_id uuid,
  pattern_type text not null,
  pattern text not null,
  mechanism text,
  lasean_adaptation text,
  copy_risk text,
  evidence jsonb default '[]'::jsonb not null,
  confidence numeric(4,3),
  created_at timestamp with time zone default now() not null,
  constraint creator_pattern_evidence_pkey PRIMARY KEY (id)
);
create table research.creator_profile_capabilities (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid not null,
  capability_id uuid not null,
  strength_score numeric(5,2),
  evidence jsonb default '{}'::jsonb not null,
  notes text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint creator_profile_capabilities_pkey PRIMARY KEY (id)
);
create table research.creator_profiles (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  canonical_name text not null,
  primary_platform text,
  handle text,
  audience text,
  positioning text,
  capability_to_study text,
  strengths jsonb default '[]'::jsonb not null,
  weaknesses jsonb default '[]'::jsonb not null,
  last_researched_at timestamp with time zone,
  status platform.record_status default 'active'::platform.record_status not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  profile_type text default 'creator'::text not null,
  constraint creator_profiles_pkey PRIMARY KEY (id)
);
create table research.creator_research_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid,
  scope jsonb default '{}'::jsonb not null,
  status text default 'queued'::text not null,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  findings jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint creator_research_runs_pkey PRIMARY KEY (id)
);
create table research.creator_sources (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  creator_profile_id uuid,
  research_run_id uuid,
  source_url text not null,
  source_type text,
  title text,
  publisher text,
  published_at timestamp with time zone,
  captured_at timestamp with time zone default now() not null,
  content_hash text,
  metadata jsonb default '{}'::jsonb not null,
  constraint creator_sources_pkey PRIMARY KEY (id)
);
create table research.research_jobs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  research_code text not null,
  question text not null,
  research_type text,
  priority smallint,
  status platform.work_status default 'research'::platform.work_status not null,
  requested_by_person_id uuid,
  due_at timestamp with time zone,
  verified_facts jsonb default '[]'::jsonb not null,
  assumptions jsonb default '[]'::jsonb not null,
  unresolved_questions jsonb default '[]'::jsonb not null,
  conclusion text,
  confidence numeric,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint research_jobs_pkey PRIMARY KEY (id)
);
create table research.research_notes (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  research_job_id uuid not null,
  source_id uuid,
  note_type text,
  content text not null,
  claim_text text,
  verified boolean,
  confidence numeric,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint research_notes_pkey PRIMARY KEY (id)
);
create table research.research_sources (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  research_job_id uuid,
  url text,
  title text,
  publisher text,
  source_type text,
  published_at timestamp with time zone,
  accessed_at timestamp with time zone default now() not null,
  authority knowledge.source_authority default 'external'::knowledge.source_authority not null,
  reliability_score numeric,
  evidence_position text,
  excerpt text,
  notes text,
  checksum text,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint research_sources_pkey PRIMARY KEY (id)
);
create table system.acceptance_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  suite_code text default 'dre_media_core_v1'::text not null,
  status text not null,
  passed_count integer default 0 not null,
  failed_count integer default 0 not null,
  total_count integer default 0 not null,
  results jsonb default '[]'::jsonb not null,
  metadata jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint acceptance_runs_pkey PRIMARY KEY (id)
);
create table system.automation_events (
  id bigint not null,
  organization_id uuid not null,
  run_id uuid,
  event_type text not null,
  actor_type text default 'system'::text not null,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  constraint automation_events_pkey PRIMARY KEY (id)
);
create table system.automation_policies (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  policy_code text not null,
  name text not null,
  enabled boolean default true not null,
  trigger_type text not null,
  schedule text,
  action_type text not null,
  approval_mode text default 'required'::text not null,
  max_cost_usd numeric(10,2),
  configuration jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint automation_policies_pkey PRIMARY KEY (id)
);
create table system.automation_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  policy_id uuid,
  idempotency_key text,
  status text default 'queued'::text not null,
  input jsonb default '{}'::jsonb not null,
  output jsonb default '{}'::jsonb not null,
  attempt_count integer default 0 not null,
  max_attempts integer default 3 not null,
  available_at timestamp with time zone default now() not null,
  claimed_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  cost_usd numeric(10,4),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint automation_runs_pkey PRIMARY KEY (id)
);
create table system.deployments (
  id uuid default gen_random_uuid() not null,
  deployment_name text not null,
  version text not null,
  environment text default 'production'::text not null,
  status text not null,
  deployed_at timestamp with time zone default now() not null,
  verified_at timestamp with time zone,
  metadata jsonb default '{}'::jsonb not null,
  constraint deployments_pkey PRIMARY KEY (id)
);
create table system.integrations (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  integration_code text not null,
  provider text not null,
  status text default 'disconnected'::text not null,
  secret_ref text,
  capabilities text[] default '{}'::text[] not null,
  configuration jsonb default '{}'::jsonb not null,
  last_health_at timestamp with time zone,
  last_error text,
  connected_by uuid,
  connected_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint integrations_pkey PRIMARY KEY (id)
);
create table system.mcp_access_tokens (
  id uuid default gen_random_uuid() not null,
  client_id text not null,
  token_hash text not null,
  refresh_token_hash text,
  user_id uuid not null,
  organization_id uuid not null,
  expires_at timestamp with time zone not null,
  refresh_expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  constraint mcp_access_tokens_pkey PRIMARY KEY (id)
);
create table system.mcp_auth_codes (
  code text not null,
  client_id text not null,
  redirect_uri text not null,
  code_challenge text not null,
  code_challenge_method text default 'S256'::text not null,
  user_id uuid not null,
  organization_id uuid not null,
  expires_at timestamp with time zone not null,
  used_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  constraint mcp_auth_codes_pkey PRIMARY KEY (code)
);
create table system.mcp_oauth_clients (
  client_id text not null,
  client_name text not null,
  redirect_uris text[] not null,
  created_at timestamp with time zone default now() not null,
  constraint mcp_oauth_clients_pkey PRIMARY KEY (client_id)
);
create table system.production_compiler_acceptance_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  episode_id uuid,
  compiler_version integer not null,
  checks jsonb default '[]'::jsonb not null,
  passed boolean default false not null,
  created_at timestamp with time zone default now() not null,
  constraint production_compiler_acceptance_runs_pkey PRIMARY KEY (id)
);
create table system.stage_gate_definitions (
  stage_code text not null,
  pass_if jsonb not null,
  fail_if jsonb not null,
  evidence_required text[] default '{}'::text[] not null,
  retry_policy jsonb default '{"backoff": "exponential", "max_attempts": 3}'::jsonb not null,
  human_review_if jsonb default '[]'::jsonb not null,
  active boolean default true not null,
  updated_at timestamp with time zone default now() not null,
  constraint stage_gate_definitions_pkey PRIMARY KEY (stage_code)
);
create table system.workflow_definitions (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  workflow_code text not null,
  name text not null,
  domain text not null,
  version integer default 1 not null,
  stages jsonb default '[]'::jsonb not null,
  active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  constraint workflow_definitions_pkey PRIMARY KEY (id)
);
create table system.workflow_events (
  id bigint not null,
  organization_id uuid not null,
  workflow_run_id uuid not null,
  stage_code text,
  event_type text not null,
  payload jsonb default '{}'::jsonb not null,
  actor_type text default 'system'::text not null,
  actor_id text,
  created_at timestamp with time zone default now() not null,
  constraint workflow_events_pkey PRIMARY KEY (id)
);
create table system.workflow_runs (
  id uuid default gen_random_uuid() not null,
  organization_id uuid not null,
  workflow_definition_id uuid not null,
  subject_type text not null,
  subject_id uuid,
  status text default 'active'::text not null,
  current_stage text,
  context jsonb default '{}'::jsonb not null,
  started_by uuid,
  started_at timestamp with time zone default now() not null,
  completed_at timestamp with time zone,
  updated_at timestamp with time zone default now() not null,
  constraint workflow_runs_pkey PRIMARY KEY (id)
);
