CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON system.agent_jobs FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON platform.companies FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON platform.organizations FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON platform.people FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON platform.products FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON platform.projects FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON knowledge.entities FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_chunk_embedding_queue_insert AFTER INSERT ON knowledge.document_chunks FOR EACH ROW EXECUTE FUNCTION knowledge.enqueue_chunk_embedding();
CREATE TRIGGER trg_chunk_embedding_queue_update AFTER UPDATE OF content ON knowledge.document_chunks FOR EACH ROW EXECUTE FUNCTION knowledge.enqueue_chunk_embedding();
CREATE TRIGGER trg_document_chunks_invalidate_embedding BEFORE UPDATE OF content, heading_path ON knowledge.document_chunks FOR EACH ROW EXECUTE FUNCTION knowledge.invalidate_chunk_embedding();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON knowledge.documents FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON knowledge.memories FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON studio.assets FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_sync_raw_asset_ingested_state AFTER UPDATE OF status ON studio.assets FOR EACH ROW EXECUTE FUNCTION system.sync_raw_asset_ingested_state();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON studio.clips FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON studio.content_ideas FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_metrics_learning_queue AFTER INSERT ON studio.content_metrics FOR EACH ROW EXECUTE FUNCTION studio.enqueue_metrics_learning();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON studio.content_series FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_episode_status_change AFTER UPDATE OF status ON studio.episodes FOR EACH ROW EXECUTE FUNCTION studio.log_episode_status_change();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON studio.episodes FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_sync_episode_recorded_state BEFORE UPDATE OF status, metadata ON studio.episodes FOR EACH ROW EXECUTE FUNCTION system.sync_episode_recorded_state();
CREATE TRIGGER trg_capture_qc_after_transcribe AFTER UPDATE OF status, output ON studio.pipeline_stages FOR EACH ROW EXECUTE FUNCTION system.capture_qc_after_transcribe();
CREATE TRIGGER trg_inject_production_intelligence BEFORE UPDATE OF status, output ON studio.pipeline_stages FOR EACH ROW EXECUTE FUNCTION system.inject_production_intelligence_into_pipeline_stage();
CREATE TRIGGER trg_persist_edit_spec_after_plan AFTER UPDATE OF status, output ON studio.pipeline_stages FOR EACH ROW EXECUTE FUNCTION system.persist_edit_spec_after_plan();
CREATE TRIGGER trg_sync_pipeline_stage_to_production_state AFTER UPDATE OF status ON studio.pipeline_stages FOR EACH ROW EXECUTE FUNCTION system.sync_pipeline_stage_to_production_state();
CREATE TRIGGER trg_auto_capture_platform_lineage AFTER INSERT OR UPDATE OF episode_id, clip_id, title, thumbnail_asset_id ON studio.platform_posts FOR EACH ROW EXECUTE FUNCTION studio.auto_capture_platform_lineage();
CREATE TRIGGER trg_platform_post_status_change AFTER UPDATE OF status ON studio.platform_posts FOR EACH ROW EXECUTE FUNCTION studio.log_platform_post_status_change();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON studio.platform_posts FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_production_blocks_updated_at BEFORE UPDATE ON studio.production_blocks FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON studio.production_days FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_publishing_jobs_updated_at BEFORE UPDATE ON studio.publishing_jobs FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_scripts_updated_at BEFORE UPDATE ON studio.scripts FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_thumbnails_updated_at BEFORE UPDATE ON studio.thumbnails FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_creator_mechanism_to_knowledge AFTER INSERT OR UPDATE OF mechanism_name, category, description, why_it_works, lasean_adaptation, avoid, trend_dependency, success_metric, metadata ON research.creator_mechanisms FOR EACH ROW EXECUTE FUNCTION research.sync_creator_mechanism_to_knowledge();
CREATE TRIGGER trg_creator_mechanisms_updated_at BEFORE UPDATE ON research.creator_mechanisms FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_creator_profiles_updated_at BEFORE UPDATE ON research.creator_profiles FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_research_jobs_updated_at BEFORE UPDATE ON research.research_jobs FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
CREATE TRIGGER trg_research_sources_updated_at BEFORE UPDATE ON research.research_sources FOR EACH ROW EXECUTE FUNCTION platform.set_updated_at();
